static const char g_2048_qpk_js[] =
  "'use strict';\n"
  "import storage from '@system.storage';\n"
  "const viewport = ui.getSize();\n"
  "const W = viewport.width, H = viewport.height;\n"
  "const controlsY = H - 48;\n"
  "const tileGap = 8;\n"
  "const boardSize = Math.min(W - 40, controlsY - 54);\n"
  "const tileSize = Math.floor((boardSize - 16 - tileGap * 3) / 4);\n"
  "const actualBoard = tileSize * 4 + tileGap * 3 + 16;\n"
  "const boardX = Math.floor((W - actualBoard) / 2);\n"
  "const boardY = 46;\n"
  "const scoreLabel = ui.text('分数 0', 20, 10, 20, 0x776e65);\n"
  "const bestLabel = ui.text('最高 0', 150, 10, 20, 0x776e65);\n"
  "const statusLabel = ui.text('准备开始', W - 170, 12, 16, 0x776e65);\n"
  "ui.background(0xfaf8ef);\n"
  "const boardPanel = ui.panel(boardX, boardY, actualBoard, actualBoard, 0xbbada0, 10, 255);\n"
  "const tilePanels = [], tileLabels = [];\n"
  "for (let i = 0; i < 16; i++) {\n"
  "  const x = boardX + 8 + (i % 4) * (tileSize + tileGap);\n"
  "  const y = boardY + 8 + Math.floor(i / 4) * (tileSize + tileGap);\n"
  "  tilePanels.push(ui.panel(x, y, tileSize, tileSize, 0xcdc1b4, 7, 255));\n"
  "  tileLabels.push(ui.number('', x, y, tileSize, tileSize, 0x776e65));\n"
  "}\n"
  "const board = [];\n"
  "let score = 0;\n"
  "let best = 0;\n"
  "let gameOver = false;\n"
  "let won = false;\n"
  "try { const value = Number(storage.get('best') || 0); if (isFinite(value) && value > 0) best = Math.floor(value); } catch (e) {}\n"
  "function setText(handle, value) { ui.setText(handle, String(value)); }\n"
  "function tileColor(value) {\n"
  "  if (value === 2) return 0xeee4da;\n"
  "  if (value === 4) return 0xede0c8;\n"
  "  if (value === 8) return 0xf2b179;\n"
  "  if (value === 16) return 0xf59563;\n"
  "  if (value === 32) return 0xf67c5f;\n"
  "  if (value === 64) return 0xf65e3b;\n"
  "  if (value === 128) return 0xedcf72;\n"
  "  if (value === 256) return 0xedcc61;\n"
  "  if (value === 512) return 0xedc850;\n"
  "  if (value === 1024) return 0xedc53f;\n"
  "  if (value >= 2048) return 0xedc22e;\n"
  "  return 0xcdc1b4;\n"
  "}\n"
  "function textColor(value) { return value <= 4 ? 0x776e65 : 0xffffff; }\n"
  "function addTile() {\n"
  "  const empty = [];\n"
  "  for (let i = 0; i < 16; i++) if (board[i] === 0) empty.push(i);\n"
  "  if (!empty.length) return;\n"
  "  const index = empty[Math.floor(Math.random() * empty.length)];\n"
  "  board[index] = Math.random() < 0.9 ? 2 : 4;\n"
  "}\n"
  "function reset() {\n"
  "  board.length = 0;\n"
  "  for (let i = 0; i < 16; i++) board.push(0);\n"
  "  score = 0; gameOver = false; won = false; addTile(); addTile(); draw();\n"
  "}\n"
  "function slide(line) {\n"
  "  const values = [];\n"
  "  const result = [];\n"
  "  for (let i = 0; i < 4; i++) if (line[i]) values.push(line[i]);\n"
  "  for (let i = 0; i < values.length; i++) {\n"
  "    if (i + 1 < values.length && values[i] === values[i + 1]) {\n"
  "      const merged = values[i] * 2; result.push(merged); score += merged;\n"
  "      if (merged === 2048) won = true; i++;\n"
  "    } else result.push(values[i]);\n"
  "  }\n"
  "  while (result.length < 4) result.push(0);\n"
  "  for (let i = 0; i < 4; i++) if (result[i] !== line[i]) return {line:result, changed:true};\n"
  "  return {line:result, changed:false};\n"
  "}\n"
  "function move(direction) {\n"
  "  if (gameOver) return;\n"
  "  let changed = false;\n"
  "  for (let n = 0; n < 4; n++) {\n"
  "    const line = [];\n"
  "    for (let k = 0; k < 4; k++) {\n"
  "      const source = direction === 'right' || direction === 'down' ? 3 - k : k;\n"
  "      const p = direction === 'left' || direction === 'right' ? n * 4 + source : source * 4 + n;\n"
  "      line[k] = board[p];\n"
  "    }\n"
  "    const result = slide(line);\n"
  "    if (result.changed) changed = true;\n"
  "    for (let k = 0; k < 4; k++) {\n"
  "      const target = direction === 'right' || direction === 'down' ? 3 - k : k;\n"
  "      const p = direction === 'left' || direction === 'right' ? n * 4 + target : target * 4 + n;\n"
  "      board[p] = result.line[k];\n"
  "    }\n"
  "  }\n"
  "  if (!changed) { if (!canMove()) { gameOver = true; setText(statusLabel, '游戏结束'); } return; }\n"
  "  if (score > best) { best = score; try { storage.set('best', String(best)); } catch (e) {} }\n"
  "  addTile();\n"
  "  if (!canMove()) gameOver = true;\n"
  "  draw();\n"
  "}\n"
  "function canMove() {\n"
  "  for (let i = 0; i < 16; i++) {\n"
  "    if (board[i] === 0) return true;\n"
  "    if (i % 4 < 3 && board[i] === board[i + 1]) return true;\n"
  "    if (i < 12 && board[i] === board[i + 4]) return true;\n"
  "  }\n"
  "  return false;\n"
  "}\n"
  "function draw() {\n"
  "  setText(scoreLabel, '分数 ' + score); setText(bestLabel, '最高 ' + best);\n"
  "  if (gameOver) setText(statusLabel, '游戏结束'); else if (won) setText(statusLabel, '达成 2048'); else setText(statusLabel, '准备开始');\n"
  "  for (let i = 0; i < 16; i++) { const value = board[i]; ui.setColor(tilePanels[i], tileColor(value)); ui.setColor(tileLabels[i], textColor(value)); setText(tileLabels[i], value ? value : ''); }\n"
  "}\n"
  "const restart = ui.button('重新开始', 20, controlsY, 132, 42, reset, 0xf0a04b);\n"
  "const left = ui.button('左', W - 292, controlsY, 62, 42, function () { move('left'); }, 0x776e65);\n"
  "const up = ui.button('上', W - 224, controlsY, 62, 42, function () { move('up'); }, 0x776e65);\n"
  "const down = ui.button('下', W - 156, controlsY, 62, 42, function () { move('down'); }, 0x776e65);\n"
  "const right = ui.button('右', W - 88, controlsY, 62, 42, function () { move('right'); }, 0x776e65);\n"
  "ui.onSwipe(function (direction) { move(direction); });\n"
  "reset();\n";

