/* Generated from camera/app.js. SPDX-License-Identifier: Apache-2.0 */
static const char g_camera_app_js[] =
"'use strict';\n"
"\n"
"const view = ui.getSize();\n"
"const left = 24, width = view.width - 48;\n"
"// The runtime publishes the desktop's card, surface, text and accent colours.\n"
"const light = ((ui.card >> 16) & 255) + ((ui.card >> 8) & 255) + (ui.card & 255) > 384;\n"
"const colors = {\n"
"  page: ui.card, card: ui.surface, primary: ui.primary, secondary: ui.secondary,\n"
"  accent: ui.accent, onAccent: light ? 0xffffff : 0x252d46,\n"
"  border: light ? 0xcbd0e6 : 0x505975\n"
"};\n"
"const labels = new Map(), enabled = new Map();\n"
"let devices = [], selected = null, modes = [], modeIndex = 0, intervalIndex = 0;\n"
"let pending = false, running = false, requestAt = 0, message = '请选择摄像头后开始预览';\n"
"let signature = '', intervals = [], photoBaseline = '';\n"
"\n"
"function write(id, value) {\n"
"  value = String(value);\n"
"  if (labels.get(id) !== value) { ui.setText(id, value); labels.set(id, value); }\n"
"}\n"
"function label(value, x, y, w, h, font, color, center) {\n"
"  const id = ui.text(value, x, y, font, color);\n"
"  ui.setSize(id, w, h); ui.setStyle(id, {center: !!center, ellipsis: true});\n"
"  labels.set(id, value); return id;\n"
"}\n"
"function card(x, y, w, h, radius, fill) {\n"
"  const id = ui.panel(x, y, w, h, fill === undefined ? colors.card : fill);\n"
"  ui.setStyle(id, {radius: radius, borderColor: colors.border, borderWidth: 1, borderOpacity: 100});\n"
"  return id;\n"
"}\n"
"function button(value, x, y, w, h, action, primary) {\n"
"  const id = ui.button(value, x, y, w, h, action, primary ? colors.accent : colors.card);\n"
"  ui.setStyle(id, {radius: 12, borderColor: colors.border, borderWidth: primary ? 0 : 1,\n"
"    borderOpacity: 110, textColor: primary ? colors.onAccent : colors.primary, fontSize: 20});\n"
"  labels.set(id, value); return id;\n"
"}\n"
"function enable(id, value) {\n"
"  if (enabled.get(id) !== value) { ui.setStyle(id, {enabled: value}); enabled.set(id, value); }\n"
"}\n"
"\n"
"ui.background(colors.page);\n"
"const hint = label('选择摄像头，然后开始预览', left, 8, 520, 28, 16, colors.secondary);\n"
"card(view.width - 324, 4, 300, 36, 18);\n"
"const countLabel = label('正在检测摄像头', view.width - 316, 10, 284, 24, 16, colors.accent, true);\n"
"const rows = [];\n"
"for (let i = 0; i < 5; i++) {\n"
"  rows.push(button('', left, 56 + i * 62, width, 54, () => select(i), false));\n"
"  ui.setHidden(rows[i], true);\n"
"}\n"
"const empty = [card(left, 56, width, 300, 24, colors.page)];\n"
"const emptyIcon = ui.text('\\uf03e', view.width / 2 - 13, 158, 24, colors.accent, 1);\n"
"const emptyTitle = label('未检测到摄像头', left, 220, width, 32, 20, colors.primary, true);\n"
"const emptyHint = label('请连接 CSI 或支持 MJPEG 的 USB 摄像头', left, 258, width, 28, 16, colors.secondary, true);\n"
"empty.push(emptyIcon, emptyTitle, emptyHint);\n"
"function showList(list) {\n"
"  empty.forEach(id => ui.setHidden(id, list));\n"
"}\n"
"\n"
"card(left, 372, width, 96, 24);\n"
"label('视频参数', left + 24, 384, 200, 24, 16, colors.secondary);\n"
"const half = Math.floor((width - 64) / 2);\n"
"const modeButton = button('分辨率', left + 24, 412, half, 44,\n"
"  () => { if (pending || running || !modes.length) return;\n"
"    modeIndex = (modeIndex + 1) % modes.length; chooseIntervals(); }, false);\n"
"const fpsButton = button('帧率', left + 40 + half, 412, half, 44,\n"
"  () => { if (pending || running || !intervals.length) return;\n"
"    intervalIndex = (intervalIndex + 1) % intervals.length; renderMode(); }, false);\n"
"const status = label(message, left, 478, 520, 32, 16, colors.secondary);\n"
"const startButton = button('开始预览', 486, 488, 200, 48, start, true);\n"
"const refreshButton = button('刷新设备', 702, 488, 160, 48, () => refresh(true), false);\n"
"const stopButton = button('停止', 878, 488, 120, 48, stop, false);\n"
"\n"
"function key(d) { return d.id + ':' + d.generation; }\n"
"function setStatus(value) { message = value; write(status, value); }\n"
"function controls(busy) {\n"
"  busy = busy || pending || running || system.camera.status().busy;\n"
"  enable(startButton, !busy && !!selected && !!selected.previewSupported);\n"
"  enable(stopButton, !!busy);\n"
"  enable(refreshButton, !busy);\n"
"  enable(modeButton, !busy && modes.length > 0);\n"
"  enable(fpsButton, !busy && intervals.length > 0);\n"
"  rows.forEach(row => enable(row, !busy));\n"
"}\n"
"function renderMode() {\n"
"  const m = modes[modeIndex];\n"
"  write(modeButton, selected && selected.transport === 'csi' ? '1024 x 600 · RGB565' :\n"
"    m ? m.width + ' x ' + m.height + ' · MJPEG' : '没有可用的 MJPEG 模式');\n"
"  const interval = intervals[intervalIndex];\n"
"  write(fpsButton, selected && selected.transport === 'csi' ? '30 fps' : interval ?\n"
"    (10000000 / interval).toFixed(1) + ' fps' : '帧率不可用');\n"
"}\n"
"function chooseIntervals() {\n"
"  intervals = []; intervalIndex = 0;\n"
"  const m = modes[modeIndex];\n"
"  if (m) {\n"
"    if (m.continuous) {\n"
"      const min = m.intervals[0], max = m.intervals[1], step = m.intervals[2];\n"
"      [m.defaultInterval, min, 333333, 666666, 1000000, max].forEach(v => {\n"
"        let n = Math.max(min, Math.min(max, v));\n"
"        if (step) n = min + Math.floor((n - min) / step) * step;\n"
"        if (!intervals.includes(n)) intervals.push(n);\n"
"      });\n"
"    } else intervals = m.intervals.slice();\n"
"    const preferred = intervals.findIndex(v => v >= 666666);\n"
"    intervalIndex = preferred >= 0 ? preferred : Math.max(0, intervals.indexOf(m.defaultInterval));\n"
"  }\n"
"  renderMode();\n"
"}\n"
"function select(index) {\n"
"  if (pending || running || system.camera.status().busy || !devices[index]) return;\n"
"  selected = devices[index]; modes = []; modeIndex = 0;\n"
"  if (selected.transport === 'usb') {\n"
"    try { modes = system.camera.modes(selected.id, selected.generation); }\n"
"    catch (_) { setStatus('设备已断开，请刷新'); selected = null; }\n"
"    let best = modes.findIndex(m => m.width === 640 && m.height === 480);\n"
"    if (best < 0) best = modes.findIndex(m => m.width <= 1280 && m.height <= 720);\n"
"    if (best >= 0) modeIndex = best;\n"
"  }\n"
"  chooseIntervals();\n"
"  if (selected) setStatus('已选择 ' + shortName(selected.name));\n"
"  renderRows(); controls(); renderMode();\n"
"}\n"
"function shortName(name) {\n"
"  const text = Array.from(name || '');\n"
"  return (text.length > 28 ? text.slice(0, 27).join('') + '…' : text.join(''));\n"
"}\n"
"function renderRows() {\n"
"  for (let i = 0; i < rows.length; i++) {\n"
"    const d = devices[i];\n"
"    ui.setHidden(rows[i], !d);\n"
"    if (!d) continue;\n"
"    const current = selected && key(d) === key(selected);\n"
"    ui.setColor(rows[i], current ? colors.accent : colors.card);\n"
"    ui.setStyle(rows[i], {borderWidth: current ? 0 : 1,\n"
"      textColor: current ? colors.onAccent : colors.primary});\n"
"    write(rows[i], shortName(d.name) + ' · ' + d.transport.toUpperCase() +\n"
"      (d.previewSupported ? '' : ' · 不支持预览'));\n"
"  }\n"
"  showList(devices.length > 0);\n"
"  const csi = devices.filter(d => d.transport === 'csi').length;\n"
"  write(countLabel, devices.length ? '已连接 ' + devices.length + ' 个摄像头 · USB ' +\n"
"    (devices.length - csi) + ' / CSI ' + csi : '未连接摄像头');\n"
"  write(emptyTitle, '未检测到摄像头');\n"
"  controls();\n"
"}\n"
"function refresh(force) {\n"
"  let current;\n"
"  try { current = system.camera.devices(); }\n"
"  catch (_) { setStatus('设备查询失败，请重试'); return; }\n"
"  const next = current.map(key).join(',');\n"
"  if (!force && next === signature) return;\n"
"  signature = next; devices = current;\n"
"  if (selected && !devices.some(d => key(d) === key(selected))) {\n"
"    pending = false; system.camera.stop(); running = false; selected = null;\n"
"    modes = []; intervals = []; setStatus('摄像头已断开，请重新选择');\n"
"  }\n"
"  if (!selected && devices.length && !system.camera.status().busy) select(0);\n"
"  renderRows(); renderMode();\n"
"  if (!devices.length && !pending) setStatus('未检测到摄像头，请连接 CSI 或 USB 摄像头');\n"
"  controls();\n"
"}\n"
"function start() {\n"
"  if (pending || running || system.camera.status().busy) return;\n"
"  refresh(false);\n"
"  if (!selected || !selected.previewSupported) { setStatus('请选择可预览的摄像头'); return; }\n"
"  if (selected.transport === 'usb' && !modes.length) { setStatus('该摄像头没有可用的 MJPEG 模式'); return; }\n"
"  const photo = system.camera.photoStatus();\n"
"  photoBaseline = photo && photo.path ? photo.path : '';\n"
"  system.camera.stop(); pending = true; requestAt = Date.now();\n"
"  setStatus('正在准备预览…'); controls();\n"
"}\n"
"function stop() {\n"
"  pending = false; running = false; system.camera.stop();\n"
"  setStatus(stoppedStatus(0)); controls();\n"
"}\n"
"// The live preview paints its own toolbar, so the saved path is reported on\n"
"// the page after the preview closes.\n"
"function stoppedStatus(error) {\n"
"  if (error) return '预览已停止（' + error + '），请检查连接或更换视频模式';\n"
"  const photo = system.camera.photoStatus() || {};\n"
"  if (photo.status === 2 && photo.path && photo.path !== photoBaseline)\n"
"    return '照片已保存 · ' + photo.path;\n"
"  if (photo.status === -125) return '已取消拍照';\n"
"  if (photo.status < 0 && !photo.path) return '拍照失败（' + photo.status + '）';\n"
"  return '预览已停止';\n"
"}\n"
"function tick() {\n"
"  const state = system.camera.status();\n"
"  if (pending) {\n"
"    if (Date.now() - requestAt > 10000) {\n"
"      pending = false; setStatus('相机释放超时，请稍后重试'); controls(); return;\n"
"    }\n"
"    if (state.busy) return;\n"
"    pending = false;\n"
"    const m = modes[modeIndex];\n"
"    running = system.camera.startDevice(selected.id, selected.generation,\n"
"      m ? m.index : 0, intervals[intervalIndex] || 0);\n"
"    if (!running) setStatus('启动失败，请刷新设备后重试');\n"
"    controls();\n"
"    return;\n"
"  }\n"
"  if (running && !state.busy) {\n"
"    running = false;\n"
"    setStatus(stoppedStatus(state.error));\n"
"    controls();\n"
"  }\n"
"  refresh(false);\n"
"}\n"
"refresh(true);\n"
"setInterval(tick, 500);\n"
"globalThis.CameraPreview = { start, stop, refresh: () => refresh(true), frames: () => system.camera.frames() };\n";
const char *camera_get_app_js(unsigned int *len) { *len=sizeof(g_camera_app_js)-1; return g_camera_app_js; }
