/* Generated from espdl/app.js. SPDX-License-Identifier: Apache-2.0 */
static const char g_espdl_app_js[] =
"'use strict';\n"
"const size = ui.getSize(), dl = system.espdl;\n"
"const names = ['物体分类', '人脸跟随'];\n"
"// The runtime publishes the same card, surface, text and accent colours the\n"
"// desktop uses, so the app follows the current theme without hardcoding it.\n"
"const light = ((ui.card >> 16) & 255) + ((ui.card >> 8) & 255) + (ui.card & 255) > 384;\n"
"const colors = {\n"
"  background: ui.card, card: ui.surface, inset: ui.card, primary: ui.primary,\n"
"  secondary: ui.secondary, accent: ui.accent, onAccent: light ? 0xffffff : 0x252d46,\n"
"  border: light ? 0xcbd0e6 : 0x505975,\n"
"  good: light ? 0x237f73 : 0x7bd8bb, error: light ? 0xa53949 : 0xffa4af\n"
"};\n"
"let mode = 1, request = 0, frame = 0, devices = [], deviceIndex = 0, switching = false;\n"
"let afterStop = '', lastDeviceCheck = 0, fpsStart = 0, fpsFrame = 0, fps = '--';\n"
"const labels = new Map(), enabled = new Map();\n"
"function write(id, value) {\n"
"  value = String(value);\n"
"  if (labels.get(id) !== value) { ui.setText(id, value); labels.set(id, value); }\n"
"}\n"
"function label(value, x, y, w, h, font = 16, color = colors.primary, center = false) {\n"
"  const id = ui.text(value, x, y, font, color);\n"
"  ui.setSize(id, w, h); ui.setStyle(id, {center, ellipsis: true});\n"
"  labels.set(id, value); return id;\n"
"}\n"
"function card(x, y, w, h, fill = colors.card, radius = 24) {\n"
"  const id = ui.panel(x, y, w, h, fill);\n"
"  ui.setStyle(id, {radius, borderColor: colors.border, borderWidth: 1, borderOpacity: 100});\n"
"  return id;\n"
"}\n"
"function button(value, x, y, w, action, primary = false, h = 48) {\n"
"  const id = ui.button(value, x, y, w, h, action, primary ? colors.accent : colors.card);\n"
"  ui.setStyle(id, {radius: 12, borderColor: colors.border, borderWidth: primary ? 0 : 1,\n"
"    borderOpacity: 110, textColor: primary ? colors.onAccent : colors.primary, fontSize: 20});\n"
"  labels.set(id, value); return id;\n"
"}\n"
"function enable(id, value) {\n"
"  if (enabled.get(id) !== value) { ui.setStyle(id, {enabled: value}); enabled.set(id, value); }\n"
"}\n"
"ui.background(colors.background);\n"
"card(24, 4, 320, 48, colors.card, 16);\n"
"const buttons = [];\n"
"[1, 0].forEach((i, position) => {\n"
"  buttons[i] = button(names[i], 28 + position * 158, 8, 154, () => selectMode(i), false, 40);\n"
"});\n"
"const modeHint = label('选择模式后点击开始', 364, 18, 260, 24, 16, colors.secondary);\n"
"card(size.width - 188, 8, 164, 36, colors.card, 18);\n"
"label('本地识别 · 无需联网', size.width - 184, 14, 156, 24, 16, colors.accent, true);\n"
"\n"
"const bodyY = 64, footerY = size.height - 64, bodyH = footerY - bodyY - 16;\n"
"const leftW = Math.min(512, Math.floor((size.width - 64) * 0.54));\n"
"const rightX = 24 + leftW + 16, rightW = size.width - rightX - 24;\n"
"card(24, bodyY, leftW, bodyH);\n"
"// Integral scale steps keep the display aspect ratio exactly 4:3.\n"
"const previewW = Math.min(480, Math.floor(Math.min(leftW - 32, (bodyH - 32) * 4 / 3) / 40) * 40);\n"
"const previewH = previewW * 3 / 4;\n"
"const previewX = 24 + Math.floor((leftW - previewW) / 2);\n"
"const previewY = bodyY + Math.floor((bodyH - previewH) / 2);\n"
"const centerX = 24 + leftW / 2, centerY = bodyY + bodyH / 2;\n"
"const placeholder = [card(centerX - 36, centerY - 76, 72, 72, colors.inset, 24)];\n"
"// LV_SYMBOL_EYE_OPEN for following, LV_SYMBOL_IMAGE for classification.\n"
"const modeIcon = ui.text('\\uf06e', centerX - 12, centerY - 52, 24, colors.accent, 1);\n"
"placeholder.push(modeIcon);\n"
"const emptyTitle = label('相机已就绪', 44, centerY + 16, leftW - 40, 32, 20, colors.primary, true);\n"
"const emptyHint = label('点击开始跟随，查看实时画面', 44, centerY + 56, leftW - 40, 28, 16, colors.secondary, true);\n"
"placeholder.push(emptyTitle, emptyHint);\n"
"const preview = dl.preview(previewX, previewY, previewW);\n"
"ui.setHidden(preview, true);\n"
"let previewVisible = false;\n"
"function showPreview(show) {\n"
"  if (previewVisible === show) return;\n"
"  previewVisible = show;\n"
"  ui.setHidden(preview, !show); placeholder.forEach(id => ui.setHidden(id, show));\n"
"}\n"
"\n"
"const resultH = bodyH - 116;\n"
"card(rightX, bodyY, rightW, resultH);\n"
"const section = label('跟随状态', rightX + 24, bodyY + 16, rightW - 48, 24, 16, colors.secondary);\n"
"const title = label('', rightX + 24, bodyY + 48, rightW - 48, 40, 28);\n"
"const detail = label('', rightX + 24, bodyY + 92, rightW - 48, 40, 16, colors.secondary);\n"
"const rows = [];\n"
"for (let i = 0; i < 3; i++) {\n"
"  const y = bodyY + 140 + i * 36;\n"
"  const name = label('', rightX + 24, y, rightW - 146, 28);\n"
"  const value = label('--', rightX + rightW - 114, y, 90, 28, 16, colors.accent);\n"
"  const line = ui.rect(rightX + 24, y + 30, rightW - 48, 2, colors.border);\n"
"  const bar = ui.rect(rightX + 24, y + 30, 1, 2, colors.accent);\n"
"  ui.setHidden(bar, true);\n"
"  rows.push({name, value, line, bar});\n"
"}\n"
"const deviceY = bodyY + resultH + 16;\n"
"card(rightX, deviceY, rightW, 100);\n"
"label('当前相机', rightX + 20, deviceY + 12, rightW - 40, 24, 16, colors.secondary);\n"
"const source = button('检测相机', rightX + 16, deviceY + 42, rightW - 32, cycleDevice, false, 44);\n"
"const status = label('请选择相机后开始', 24, footerY + 4, leftW, 44, 16, colors.secondary);\n"
"const startButton = button('开始跟随', rightX, footerY, rightW - 116, start, true);\n"
"const stopButton = button('停止', rightX + rightW - 104, footerY, 104, cancel);\n"
"\n"
"function setStatus(value, error = false) {\n"
"  write(status, value); ui.setColor(status, error ? colors.error : colors.secondary);\n"
"}\n"
"function controls(busy = dl.status().busy) {\n"
"  enable(startButton, !busy && !switching && devices.length > 0);\n"
"  enable(stopButton, !!busy && !switching);\n"
"  enable(source, !busy && !switching);\n"
"}\n"
"function refreshDevices() {\n"
"  const selected = devices[deviceIndex];\n"
"  try { devices = system.camera.devices().filter(d => d.transport === 'usb' && d.previewSupported); }\n"
"  catch (_) { devices = []; }\n"
"  const index = selected ? devices.findIndex(d => d.id === selected.id && d.generation === selected.generation) : 0;\n"
"  deviceIndex = Math.max(0, index); lastDeviceCheck = Date.now(); showDevice();\n"
"}\n"
"function showDevice() {\n"
"  write(source, devices.length ? Array.from(devices[deviceIndex].name).slice(0, 32).join('') : '未连接 USB 相机 · 点击刷新');\n"
"  write(emptyTitle, devices.length ? '相机已就绪' : '等待连接相机');\n"
"  write(emptyHint, devices.length ? (mode ? '点击开始跟随，查看实时画面' : '将物体对准相机，点击拍摄并分类') : '连接 USB 相机后即可开始');\n"
"  controls();\n"
"}\n"
"function cycleDevice() {\n"
"  if (dl.status().busy || switching) return;\n"
"  refreshDevices();\n"
"  if (devices.length > 1) deviceIndex = (deviceIndex + 1) % devices.length;\n"
"  showDevice();\n"
"}\n"
"function resetRows() {\n"
"  rows.forEach((row, i) => {\n"
"    write(row.name, mode ? ['横向偏移', '纵向偏移', '画面内人脸'][i] : '候选类别 ' + (i + 1));\n"
"    write(row.value, '--'); ui.setHidden(row.bar, true);\n"
"  });\n"
"}\n"
"function describeMode() {\n"
"  buttons.forEach((id, i) => {\n"
"    ui.setColor(id, mode === i ? colors.accent : colors.card);\n"
"    ui.setStyle(id, {borderWidth: 0, textColor: mode === i ? colors.onAccent : colors.secondary});\n"
"  });\n"
"  write(startButton, mode ? '开始跟随' : '拍摄并分类');\n"
"  write(modeIcon, mode ? '\\uf06e' : '\\uf03e');\n"
"  write(modeHint, mode ? '人脸跟随 · 实时本地推理' : '物体分类 · 拍摄一帧识别');\n"
"  write(section, mode ? '跟随状态' : '分类结果');\n"
"  write(title, mode ? '让人脸进入画面' : '发现眼前的物体');\n"
"  write(detail, mode ? '自动标记目标，持续显示位置与方向' : '拍摄一帧，查看最可能的三种类别');\n"
"  resetRows(); showDevice();\n"
"}\n"
"function selectMode(next) {\n"
"  if ((next !== 0 && next !== 1) || mode === next) return;\n"
"  dl.cancel(); dl.clear(); request = frame = 0; switching = dl.status().busy; mode = next;\n"
"  showPreview(false); afterStop = names[mode] + ' · 已就绪';\n"
"  describeMode(); setStatus(switching ? '正在切换模式…' : afterStop);\n"
"}\n"
"function errorMessage(error) {\n"
"  if (error === -16) return '设备正忙，请稍后重试';\n"
"  if (error === -19 || error === -116) return '相机已断开，请重新连接';\n"
"  if (error === -2 || error === -74) return '识别模型不可用，请检查模型包';\n"
"  if (error === -12) return '内存不足，请关闭应用后重试';\n"
"  if (error === -110) return '相机取帧超时，请检查连接';\n"
"  if (error === -95) return '暂不支持当前相机模式';\n"
"  if (error === -125) return '已停止';\n"
"  return '识别失败（' + error + '），可重试';\n"
"}\n"
"function start() {\n"
"  if (dl.status().busy || switching) return;\n"
"  refreshDevices();\n"
"  const device = devices[deviceIndex];\n"
"  if (!device) { setStatus('请连接 USB 相机后重试', true); return; }\n"
"  dl.clear(); showPreview(false); frame = 0; resetRows();\n"
"  fpsStart = Date.now(); fpsFrame = 0; fps = '--';\n"
"  request = dl.start(mode, device.id, device.generation);\n"
"  if (request <= 0) { setStatus(errorMessage(request), true); request = 0; controls(); return; }\n"
"  write(title, mode ? '正在寻找人脸' : '正在识别物体');\n"
"  write(detail, mode ? '让人脸正对相机，并保持光线充足' : '请稍候，结果将在这里显示');\n"
"  write(emptyTitle, '正在获取画面'); write(emptyHint, '请保持相机连接'); controls(); tick();\n"
"}\n"
"function cancel() {\n"
"  dl.cancel(); dl.clear(); request = frame = 0; switching = dl.status().busy;\n"
"  afterStop = '已停止 · 可以重新开始'; showPreview(false); describeMode();\n"
"  setStatus(switching ? '正在停止…' : afterStop); controls();\n"
"}\n"
"function showResult(state) {\n"
"  if (mode === 0) {\n"
"    write(title, state.items.length ? state.items[0].label : '没有识别结果');\n"
"    write(detail, '前三个候选类别 · 分数表示模型置信度');\n"
"    rows.forEach((row, i) => {\n"
"      const item = state.items[i];\n"
"      write(row.name, item ? item.label : '候选类别 ' + (i + 1));\n"
"      write(row.value, item ? (item.score * 100).toFixed(1) + '%' : '--');\n"
"      ui.setHidden(row.bar, !item || item.score <= 0);\n"
"      if (item) ui.setSize(row.bar, Math.max(1, Math.round((rightW - 48) * Math.min(1, Math.max(0, item.score)))), 2);\n"
"    });\n"
"    return;\n"
"  }\n"
"  const t = state.track, tracking = t.state === 1;\n"
"  if (!tracking) {\n"
"    write(title, t.state === 2 ? '目标暂时丢失' : '正在寻找人脸');\n"
"    write(detail, t.state === 2 ? '等待原目标重新进入画面' : '请正对相机，并保持光线充足');\n"
"  } else {\n"
"    const direction = [];\n"
"    if (t.offsetX) direction.push(t.offsetX > 0 ? '向右' : '向左');\n"
"    if (t.offsetY) direction.push(t.offsetY > 0 ? '向下' : '向上');\n"
"    write(title, direction.join(' / ') || '目标已居中');\n"
"    write(detail, '正在跟随目标 ' + t.id + ' · 绿色框标记位置');\n"
"  }\n"
"  write(rows[0].value, tracking ? (t.offsetX / 10).toFixed(1) + '%' : '--');\n"
"  write(rows[1].value, tracking ? (t.offsetY / 10).toFixed(1) + '%' : '--');\n"
"  write(rows[2].value, state.items.length + ' 张');\n"
"}\n"
"function tick() {\n"
"  const state = dl.status();\n"
"  if (switching) {\n"
"    if (!state.busy) { switching = false; setStatus(afterStop); controls(false); }\n"
"    return;\n"
"  }\n"
"  if (!request || state.request !== request) {\n"
"    if (!state.busy && Date.now() - lastDeviceCheck >= 2000) refreshDevices();\n"
"    return;\n"
"  }\n"
"  if (state.error) {\n"
"    request = 0; dl.clear(); showPreview(false); resetRows();\n"
"    write(title, state.error === -125 ? '已停止' : '暂时无法识别');\n"
"    write(detail, errorMessage(state.error)); setStatus(errorMessage(state.error), state.error !== -125);\n"
"    refreshDevices(); return;\n"
"  }\n"
"  if (state.preview && state.frame !== frame) {\n"
"    // Only display results after their matching image has been copied successfully.\n"
"    if (!dl.render(request, state.frame)) return;\n"
"    frame = state.frame; showPreview(true); showResult(state);\n"
"    const now = Date.now();\n"
"    if (now - fpsStart >= 1000) {\n"
"      fps = ((frame - fpsFrame) * 1000 / (now - fpsStart)).toFixed(1);\n"
"      fpsStart = now; fpsFrame = frame;\n"
"    }\n"
"    setStatus(mode ? '正在跟随 · ' + fps + ' fps' : '分类完成 · 可再次拍摄');\n"
"  } else if (!frame && state.busy) {\n"
"    setStatus(['', '正在采集画面…', '正在准备识别…', '正在识别…'][state.stage] || '正在处理…');\n"
"  }\n"
"  controls(state.busy);\n"
"  if (!state.busy) request = 0;\n"
"}\n"
"describeMode(); refreshDevices(); setInterval(tick, 50);\n"
"globalThis.EspDlApp = {start, cancel, selectMode, status: () => dl.status()};\n";
const char *espdl_get_app_js(unsigned int *len) { *len=sizeof(g_espdl_app_js)-1; return g_espdl_app_js; }
