/* Generated from homeassistant/app.js. SPDX-License-Identifier: Apache-2.0 */
static const char g_homeassistant_app_js[] =
"/* SPDX-License-Identifier: Apache-2.0 */\n"
"'use strict';\n"
"\n"
"(function () {\n"
"  const nativeService = system.homeAssistantService;\n"
"  const sharedReady = nativeService && nativeService.apiVersion === 1 &&\n"
"    ['configure', 'get', 'getState', 'control', 'poll', 'close', 'status']\n"
"      .every(name => typeof nativeService[name] === 'function');\n"
"  const bridge = nativeService ? (sharedReady ? sharedAdapter() : {}) : system.homeAssistant;\n"
"  const storage = system.storage;\n"
"  const bridgeReady = bridge && ['get', 'getState', 'callService', 'poll']\n"
"    .every(name => typeof bridge[name] === 'function');\n"
"  const MAX_ENTITIES = 128;\n"
"  const MAX_FAVORITES = 16;\n"
"  const RESPONSE_LIMIT = 65536;\n"
"  const REQUEST_TIMEOUT = 12000;\n"
"  const REFRESH_INTERVAL = 10000;\n"
"  const VERIFY_INTERVAL = 1000;\n"
"  const VERIFY_WINDOW = 8000;\n"
"  const VERIFY_ATTEMPTS = 4;\n"
"  const BUTTON_SLOTS = 16;\n"
"  const buttons = [];\n"
"  const buttonPool = [];\n"
"  const size = ui.getSize();\n"
"  const W = size.width, H = size.height;\n"
"  const dark = ui.primary === 0xffffff;\n"
"  const colors = {\n"
"    background: dark ? 0x101318 : 0xf3f5f8,\n"
"    surface: dark ? 0x1d222b : 0xffffff,\n"
"    active: dark ? 0x3c2d20 : 0xfff0e4,\n"
"    hero: dark ? 0x32271f : 0xffe4cf,\n"
"    heroMuted: dark ? 0xcab39d : 0x8b5b36,\n"
"    sensor: dark ? 0x1c2f33 : 0xe3f1ef,\n"
"    detail: dark ? 0x171c24 : 0xf7f8fa,\n"
"    text: dark ? 0xf7f8fa : 0x15171a,\n"
"    muted: dark ? 0x9da5b2 : 0x6f7782,\n"
"    accent: dark ? 0xff7a1a : 0xff6900,\n"
"    selected: dark ? 0x4b321f : 0xffe2cc,\n"
"    good: dark ? 0x68d39b : 0x148054,\n"
"    warning: dark ? 0xf2be63 : 0xa36100\n"
"  };\n"
"  const styles = {\n"
"    icon: { radius: 18, borderWidth: 0 },\n"
"    tab: { radius: 16, borderWidth: 0, fontSize: 15 },\n"
"    card: { radius: 18, borderWidth: 0 },\n"
"    control: { radius: 14, borderWidth: 0, fontSize: 16 },\n"
"    setting: { radius: 14, borderWidth: 0, fontSize: 15 },\n"
"    panel: { radius: 18, borderWidth: 0 }\n"
"  };\n"
"  const glyph = {\n"
"    search: '\\uf002', refresh: '\\uf021', settings: '\\uf013',\n"
"    previous: '\\uf053', next: '\\uf054', favorite: '\\uf067', followed: '\\uf00c',\n"
"    light: '\\uf0e7', switch: '\\uf011', input_boolean: '\\uf205', fan: '\\uf2dc',\n"
"    sensor: '\\uf2c9', binary_sensor: '\\uf06a', home: '\\uf015'\n"
"  };\n"
"  let url = 'http://homeassistant.local:8123';\n"
"  let token = '';\n"
"  let httpAllowed = false;\n"
"  let favorites = [];\n"
"  let scope = 'all';\n"
"  let entities = [];\n"
"  let services = Object.create(null);\n"
"  let serviceDiscoveryLimited = false;\n"
"  let selectedId = '';\n"
"  let filter = 'all';\n"
"  let search = '';\n"
"  let page = 0;\n"
"  let settingsOpen = false;\n"
"  let detailOpen = false;\n"
"  let connected = false;\n"
"  let phase = 'disconnected';\n"
"  let message = '未连接';\n"
"  let generation = 0;\n"
"  let pending = null;\n"
"  let queued = null;\n"
"  let nativeBusy = false;\n"
"  let autoRefresh = false;\n"
"  let failures = 0;\n"
"  let nextRefresh = Infinity;\n"
"  let lastSync = 0;\n"
"  let lastCached = false;\n"
"  let disposed = false;\n"
"  let limited = false;\n"
"  let watchQueue = [];\n"
"  let watchResults = [];\n"
"  let timer;\n"
"  let widgets;\n"
"  let nativeManaged = false;\n"
"\n"
"  function sharedAdapter() {\n"
"    let requestId = 0, detached = false;\n"
"    function prepare() {\n"
"      detached = false;\n"
"      if (token) {\n"
"        if (nativeService.configure(url, token, httpAllowed) !== 0) return false;\n"
"        token = '';\n"
"        httpAllowed = false;\n"
"        nativeManaged = true;\n"
"      }\n"
"      const status = nativeService.status();\n"
"      nativeManaged = status.configured && parseUrl(status.url) === url;\n"
"      return nativeManaged;\n"
"    }\n"
"    function submit(action) {\n"
"      if (!prepare()) return false;\n"
"      const id = action();\n"
"      if (!Number.isInteger(id) || id <= 0) return false;\n"
"      requestId = id;\n"
"      return true;\n"
"    }\n"
"    function close() {\n"
"      detached = true;\n"
"      requestId = 0;\n"
"      nativeService.close();\n"
"    }\n"
"    return {\n"
"      get: (_url, _token, resource) => submit(() => nativeService.get(resource)),\n"
"      getState: (_url, _token, entity) => submit(() => nativeService.getState(entity)),\n"
"      callService: (_url, _token, domain, service, data) => {\n"
"        const body = JSON.parse(data);\n"
"        if (!validEntity(body.entity_id) || body.entity_id.split('.')[0] !== domain ||\n"
"            !['turn_on', 'turn_off'].includes(service) ||\n"
"            Object.keys(body).some(key => !['entity_id', 'brightness_pct'].includes(key))) return false;\n"
"        return submit(() => nativeService.control(body.entity_id, service === 'turn_on',\n"
"          body.brightness_pct === undefined ? -1 : body.brightness_pct));\n"
"      },\n"
"      poll: () => {\n"
"        if (detached) return { busy: false, done: false };\n"
"        const result = nativeService.poll();\n"
"        if (result.done && result.requestId !== requestId)\n"
"          return { busy: false, done: true, error: -22, status: 0, body: '' };\n"
"        return result;\n"
"      },\n"
"      close, stop: close\n"
"    };\n"
"  }\n"
"\n"
"  function sharedConnection() {\n"
"    if (!sharedReady) return false;\n"
"    try {\n"
"      const status = nativeService.status();\n"
"      nativeManaged = status.configured && parseUrl(status.url) === url;\n"
"      return nativeManaged;\n"
"    } catch (_) {\n"
"      nativeManaged = false;\n"
"      return false;\n"
"    }\n"
"  }\n"
"\n"
"  function clean(value, limit) {\n"
"    return typeof value === 'string' ?\n"
"      Array.from(value.replace(/[\\u0000-\\u001f\\u007f]/g, ' '))\n"
"        .slice(0, limit).join('') : '';\n"
"  }\n"
"\n"
"  function validEntity(value) {\n"
"    return typeof value === 'string' && value.length < 96 &&\n"
"      /^[a-z][a-z0-9_]*\\.[a-z0-9_]+$/.test(value);\n"
"  }\n"
"\n"
"  function parseUrl(value) {\n"
"    if (typeof value !== 'string' || value.length > 120) return '';\n"
"    const match = /^http:\\/\\/([a-zA-Z0-9.-]+)(?::([0-9]{1,5}))?\\/?$/.exec(value.trim());\n"
"    if (!match) return '';\n"
"    const host = match[1].toLowerCase();\n"
"    const port = match[2] ? Number(match[2]) : 8123;\n"
"    if (port < 1 || port > 65535) return '';\n"
"    let local = host === 'localhost';\n"
"    if (/^[0-9.]+$/.test(host)) {\n"
"      const pieces = host.split('.');\n"
"      if (pieces.length !== 4 ||\n"
"          pieces.some(x => String(Number(x)) !== x || Number(x) > 255)) return '';\n"
"      const a = pieces.map(Number);\n"
"      local = a[0] === 10 || a[0] === 127 ||\n"
"        (a[0] === 192 && a[1] === 168) ||\n"
"        (a[0] === 172 && a[1] >= 16 && a[1] <= 31) ||\n"
"        (a[0] === 169 && a[1] === 254);\n"
"    } else if (host.endsWith('.local') || host.endsWith('.lan')) {\n"
"      local = host.split('.').every(x =>\n"
"        x.length > 0 && x.length < 64 && /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/.test(x));\n"
"    }\n"
"    return local ? 'http://' + host + ':' + port : '';\n"
"  }\n"
"\n"
"  function save(key, value) {\n"
"    try {\n"
"      if (storage && typeof storage.set === 'function') storage.set(key, value);\n"
"      return true;\n"
"    } catch (_) {\n"
"      message = '本地保存失败，本次会话仍可使用';\n"
"      return false;\n"
"    }\n"
"  }\n"
"\n"
"  try {\n"
"    if (storage && typeof storage.get === 'function') {\n"
"      url = parseUrl(storage.get('eh_url')) || url;\n"
"      const saved = JSON.parse(storage.get('eh_favs') || '[]');\n"
"      if (Array.isArray(saved)) {\n"
"        favorites = saved.filter(validEntity)\n"
"          .filter((id, index, list) => list.indexOf(id) === index)\n"
"          .slice(0, MAX_FAVORITES);\n"
"      }\n"
"      scope = storage.get('eh_scope') === 'favorites' ? 'favorites' : 'all';\n"
"    }\n"
"  } catch (_) {\n"
"    message = '本地设置无法读取';\n"
"  }\n"
"\n"
"  if (sharedReady) {\n"
"    try {\n"
"      const status = nativeService.status();\n"
"      if (status.configured && parseUrl(status.url)) {\n"
"        url = parseUrl(status.url);\n"
"        nativeManaged = true;\n"
"        message = '本地 HA 服务已配置，尚未同步';\n"
"      }\n"
"    } catch (_) { message = '本地 HA 服务暂不可用'; }\n"
"  }\n"
"  // A remembered native connection should open directly to the home view and\n"
"  // begin its first bounded sync. New connections start with the setup view.\n"
"  settingsOpen = !nativeManaged;\n"
"  autoRefresh = nativeManaged;\n"
"\n"
"  function staleAll() {\n"
"    entities.forEach(item => { item.stale = true; });\n"
"  }\n"
"\n"
"  function invalidate() {\n"
"    generation++;\n"
"    queued = null;\n"
"    if (pending) pending.abandoned = true;\n"
"    connected = false;\n"
"    autoRefresh = false;\n"
"    nextRefresh = Infinity;\n"
"    lastCached = false;\n"
"    phase = 'disconnected';\n"
"    services = Object.create(null);\n"
"    serviceDiscoveryLimited = false;\n"
"    staleAll();\n"
"  }\n"
"\n"
"  function disconnect() {\n"
"    invalidate();\n"
"    token = '';\n"
"    httpAllowed = false;\n"
"    message = '已断开，令牌已从会话移除';\n"
"    if (sharedReady) {\n"
"      try { bridge.close(); } catch (_) { /* UI still invalidates its session. */ }\n"
"      nativeManaged = false;\n"
"      message = '界面已断开，本地服务配置保留';\n"
"    }\n"
"    render();\n"
"  }\n"
"\n"
"  function credentialsReady() {\n"
"    if (!bridgeReady) message = '固件未提供 Home Assistant 接口';\n"
"    else if (!parseUrl(url)) message = '需要局域网 HTTP 地址';\n"
"    else if (!token && sharedConnection()) return true;\n"
"    else if (!token) message = '尚未输入访问令牌';\n"
"    else if (!httpAllowed) message = 'HTTP 未加密，尚未授权连接';\n"
"    else return true;\n"
"    render();\n"
"    return false;\n"
"  }\n"
"\n"
"  function schedule(kind, entityId, data) {\n"
"    queued = { kind, entityId: entityId || '', data, generation };\n"
"  }\n"
"\n"
"  function startQueued() {\n"
"    if (!queued || pending || nativeBusy || disposed) return;\n"
"    if (queued.notBefore && Date.now() < queued.notBefore) return;\n"
"    const request = queued;\n"
"    queued = null;\n"
"    if (request.generation !== generation || !credentialsReady()) return;\n"
"    let accepted = false;\n"
"    try {\n"
"      if (request.kind === 'service') {\n"
"        accepted = bridge.callService(url, token, request.data.domain,\n"
"          request.data.service, JSON.stringify(request.data.body));\n"
"      } else if (request.kind === 'verify' || request.kind === 'watch') {\n"
"        accepted = bridge.getState(url, token, request.entityId);\n"
"      } else {\n"
"        accepted = bridge.get(url, token, request.kind);\n"
"      }\n"
"    } catch (_) {\n"
"      accepted = false;\n"
"    }\n"
"    if (!accepted) {\n"
"      fail(request, '接口忙或参数被拒绝', false);\n"
"      return;\n"
"    }\n"
"    pending = request;\n"
"    pending.started = Date.now();\n"
"    nativeBusy = true;\n"
"    render();\n"
"  }\n"
"\n"
"  function connect() {\n"
"    if (!credentialsReady()) return;\n"
"    if (pending || nativeBusy || queued) {\n"
"      message = '仍有请求未结束';\n"
"      render();\n"
"      return;\n"
"    }\n"
"    generation++;\n"
"    connected = false;\n"
"    phase = 'connecting';\n"
"    settingsOpen = false;\n"
"    detailOpen = false;\n"
"    selectedId = '';\n"
"    autoRefresh = true;\n"
"    failures = 0;\n"
"    services = Object.create(null);\n"
"    serviceDiscoveryLimited = false;\n"
"    staleAll();\n"
"    message = '正在连接 Home Assistant';\n"
"    schedule('config');\n"
"    startQueued();\n"
"  }\n"
"\n"
"  function refresh() {\n"
"    if (disposed || pending || nativeBusy || queued) return;\n"
"    if (!connected) { connect(); return; }\n"
"    if (!credentialsReady()) return;\n"
"    message = '正在同步状态';\n"
"    beginStates();\n"
"    startQueued();\n"
"  }\n"
"\n"
"  function beginStates() {\n"
"    if (scope === 'favorites') {\n"
"      watchQueue = favorites.slice();\n"
"      watchResults = [];\n"
"      nextWatch();\n"
"    } else {\n"
"      schedule('states');\n"
"    }\n"
"  }\n"
"\n"
"  function nextWatch() {\n"
"    if (watchQueue.length) schedule('watch', watchQueue.shift());\n"
"    else commitStates(watchResults, false, false);\n"
"  }\n"
"\n"
"  function normalize(raw, expectedId) {\n"
"    if (!raw || typeof raw !== 'object' || !validEntity(raw.entity_id) ||\n"
"        typeof raw.state !== 'string' ||\n"
"        (expectedId && raw.entity_id !== expectedId)) return null;\n"
"    const attributes = raw.attributes && typeof raw.attributes === 'object' ?\n"
"      raw.attributes : {};\n"
"    const modes = Array.isArray(attributes.supported_color_modes) ?\n"
"      attributes.supported_color_modes : [];\n"
"    const brightness = typeof attributes.brightness === 'number' &&\n"
"      Number.isFinite(attributes.brightness) &&\n"
"      attributes.brightness >= 0 && attributes.brightness <= 255 ?\n"
"      Math.round(attributes.brightness * 100 / 255) : null;\n"
"    return {\n"
"      entity_id: raw.entity_id,\n"
"      domain: raw.entity_id.split('.')[0],\n"
"      name: clean(attributes.friendly_name, 64) || raw.entity_id,\n"
"      state: clean(raw.state, 64),\n"
"      unit: clean(attributes.unit_of_measurement, 16),\n"
"      brightness,\n"
"      dimmable: raw.entity_id.startsWith('light.') &&\n"
"        (brightness !== null || modes.some(mode =>\n"
"          ['brightness', 'color_temp', 'hs', 'xy', 'rgb', 'rgbw', 'rgbww', 'white'].includes(mode))),\n"
"      stale: false\n"
"    };\n"
"  }\n"
"\n"
"  function commitStates(values, wasLimited, fromCache) {\n"
"    entities = values;\n"
"    limited = wasLimited;\n"
"    lastCached = !!fromCache;\n"
"    if (!entities.some(item => item.entity_id === selectedId)) selectedId = '';\n"
"    connected = true;\n"
"    phase = 'ready';\n"
"    failures = 0;\n"
"    lastSync = Date.now();\n"
"    nextRefresh = lastSync + REFRESH_INTERVAL;\n"
"    message = limited ? '已达 128 个实体上限，可切换关注同步' :\n"
"      '已同步 ' + entities.length + ' 个实体' +\n"
"      (lastCached ? ' · 本地缓存' : '');\n"
"    if (serviceDiscoveryLimited) message = '只读 · 服务目录超过 64 KiB' +\n"
"      (lastCached ? ' · 本地缓存' : '');\n"
"    render();\n"
"  }\n"
"\n"
"  function failureMessage(result, request) {\n"
"    if (result.error === -75 || result.error === -7) {\n"
"      if (request.kind === 'states') return '响应超过 64 KiB，请切换关注同步';\n"
"      if (request.kind === 'service' || request.kind === 'verify')\n"
"        return '控制结果未确认，请刷新；不会重试';\n"
"      return '该响应超过 64 KiB，当前固件无法读取';\n"
"    }\n"
"    if (result.error) return request.kind === 'service' ?\n"
"      '控制结果未确认，请刷新；不会重试' : '网络连接失败，状态已过期';\n"
"    if (result.status === 401 || result.status === 403) return '认证失败，请重新输入令牌';\n"
"    return request.kind === 'service' ? '控制被拒绝，HTTP ' + result.status :\n"
"      '服务返回 HTTP ' + result.status;\n"
"  }\n"
"\n"
"  function fail(request, text, auth) {\n"
"    queued = null;\n"
"    connected = false;\n"
"    phase = 'error';\n"
"    staleAll();\n"
"    message = text;\n"
"    failures++;\n"
"    if (auth) {\n"
"      generation++;\n"
"      token = '';\n"
"      httpAllowed = false;\n"
"      nativeManaged = false;\n"
"      autoRefresh = false;\n"
"    }\n"
"    const uncertain = request.kind === 'service' || request.kind === 'verify';\n"
"    nextRefresh = auth || uncertain ? Infinity :\n"
"      Date.now() + Math.min(60000, REFRESH_INTERVAL * Math.pow(2, Math.min(failures - 1, 3)));\n"
"    if (request.kind === 'verify') message = '控制结果未确认，请刷新；不会重试';\n"
"    render();\n"
"  }\n"
"\n"
"  function complete(request, result) {\n"
"    if (request.generation !== generation || request.abandoned || disposed) return;\n"
"    if (request.kind === 'services' && (result.error === -75 || result.error === -7 ||\n"
"        (!result.error && result.status >= 200 && result.status < 300 &&\n"
"         typeof result.body === 'string' && result.body.length > RESPONSE_LIMIT))) {\n"
"      services = Object.create(null);\n"
"      serviceDiscoveryLimited = true;\n"
"      message = '服务目录超限，正在只读同步';\n"
"      beginStates();\n"
"      return;\n"
"    }\n"
"    if (request.kind === 'watch' && !result.error && result.status === 404) {\n"
"      watchResults.push({\n"
"        entity_id: request.entityId, domain: request.entityId.split('.')[0],\n"
"        name: request.entityId, state: 'unavailable', unit: '',\n"
"        brightness: null, dimmable: false, stale: false\n"
"      });\n"
"      nextWatch();\n"
"      return;\n"
"    }\n"
"    if (result.error || result.status < 200 || result.status >= 300) {\n"
"      fail(request, failureMessage(result, request),\n"
"        result.status === 401 || result.status === 403);\n"
"      return;\n"
"    }\n"
"    if (request.kind === 'service') {\n"
"      message = '控制已受理，正在核对状态';\n"
"      phase = 'verifying';\n"
"      nextRefresh = Infinity;\n"
"      schedule('verify', request.entityId, {\n"
"        state: request.data.service === 'turn_on' ? 'on' : 'off',\n"
"        brightness: request.data.body.brightness_pct,\n"
"        attempt: 1,\n"
"        deadline: Date.now() + VERIFY_WINDOW\n"
"      });\n"
"      return;\n"
"    }\n"
"    try {\n"
"      if (typeof result.body !== 'string' || result.body.length > RESPONSE_LIMIT)\n"
"        throw new Error('response limit');\n"
"      const value = JSON.parse(result.body);\n"
"      if (request.kind === 'config') {\n"
"        if (!value || typeof value !== 'object' || Array.isArray(value))\n"
"          throw new Error('invalid config');\n"
"        schedule('services');\n"
"      } else if (request.kind === 'services') {\n"
"        if (!Array.isArray(value)) throw new Error('invalid services');\n"
"        const next = Object.create(null);\n"
"        value.forEach(group => {\n"
"          if (!group || typeof group.domain !== 'string' ||\n"
"              !/^[a-z_]+$/.test(group.domain) ||\n"
"              !group.services || typeof group.services !== 'object') return;\n"
"          const names = Array.isArray(group.services) ?\n"
"            group.services : Object.keys(group.services);\n"
"          names.forEach(name => {\n"
"            if (typeof name === 'string' && /^[a-z_]+$/.test(name))\n"
"              next[group.domain + '.' + name] = true;\n"
"          });\n"
"        });\n"
"        services = next;\n"
"        beginStates();\n"
"      } else if (request.kind === 'states') {\n"
"        if (!Array.isArray(value)) throw new Error('invalid states');\n"
"        const next = [];\n"
"        const seen = Object.create(null);\n"
"        let overflow = false;\n"
"        value.forEach(raw => {\n"
"          const item = normalize(raw);\n"
"          if (!item || seen[item.entity_id]) return;\n"
"          seen[item.entity_id] = true;\n"
"          if (next.length < MAX_ENTITIES) next.push(item);\n"
"          else overflow = true;\n"
"        });\n"
"        commitStates(next, overflow, !!result.cached);\n"
"      } else {\n"
"        const item = normalize(value, request.entityId);\n"
"        if (!item) throw new Error('entity mismatch');\n"
"        if (request.kind === 'watch') {\n"
"          watchResults.push(item);\n"
"          nextWatch();\n"
"        } else {\n"
"          const index = entities.findIndex(row => row.entity_id === request.entityId);\n"
"          if (index >= 0) entities[index] = item;\n"
"          const target = request.data;\n"
"          const matched = item.state === target.state &&\n"
"            (target.brightness === undefined || (item.brightness !== null &&\n"
"             Math.abs(item.brightness - target.brightness) <= 1));\n"
"          if (!matched) {\n"
"            if (target.attempt >= VERIFY_ATTEMPTS || Date.now() >= target.deadline) {\n"
"              fail(request, '控制结果未确认，请刷新；不会重试', false);\n"
"              return;\n"
"            }\n"
"            message = '等待设备达到目标状态';\n"
"            schedule('verify', request.entityId, {\n"
"              state: target.state, brightness: target.brightness,\n"
"              attempt: target.attempt + 1, deadline: target.deadline\n"
"            });\n"
"            queued.notBefore = Date.now() + VERIFY_INTERVAL;\n"
"            render();\n"
"            return;\n"
"          }\n"
"          connected = true;\n"
"          phase = 'ready';\n"
"          message = '状态已达到目标：' + item.name;\n"
"          failures = 0;\n"
"          nextRefresh = Date.now() + REFRESH_INTERVAL;\n"
"          render();\n"
"        }\n"
"      }\n"
"    } catch (_) {\n"
"      fail(request, '响应格式错误，未应用数据', false);\n"
"    }\n"
"  }\n"
"\n"
"  function tick() {\n"
"    if (disposed || !bridgeReady) return;\n"
"    if (pending && !pending.abandoned &&\n"
"        Date.now() - pending.started >= REQUEST_TIMEOUT) {\n"
"      pending.abandoned = true;\n"
"      fail(pending, pending.kind === 'service' ?\n"
"        '控制结果未确认，请刷新；不会重试' : '请求超时，等待旧请求结束', false);\n"
"    }\n"
"    // Enforce the whole confirmation window before consuming a late result.\n"
"    const verification = pending || queued;\n"
"    if (verification && verification.kind === 'verify' &&\n"
"        !verification.abandoned && Date.now() >= verification.data.deadline) {\n"
"      verification.abandoned = true;\n"
"      fail(verification, '控制结果未确认，请刷新；不会重试', false);\n"
"    }\n"
"    let result;\n"
"    try { result = bridge.poll(); }\n"
"    catch (_) {\n"
"      if (pending && !pending.abandoned) {\n"
"        pending.abandoned = true;\n"
"        fail(pending, '接口异常，等待旧请求结束', false);\n"
"      }\n"
"      return;\n"
"    }\n"
"    if (!result || typeof result !== 'object') return;\n"
"    nativeBusy = !!result.busy;\n"
"    if (pending && result.done) {\n"
"      const request = pending;\n"
"      pending = null;\n"
"      complete(request, result);\n"
"      render();\n"
"    } else if (pending && !nativeBusy && pending.abandoned) {\n"
"      pending = null;\n"
"      render();\n"
"    }\n"
"    startQueued();\n"
"    if (!pending && !queued && !nativeBusy && !settingsOpen &&\n"
"        autoRefresh && (token || sharedConnection()) && Date.now() >= nextRefresh) {\n"
"      if (connected) refresh();\n"
"      else {\n"
"        phase = 'connecting';\n"
"        message = '正在重新读取连接状态';\n"
"        schedule('config');\n"
"        startQueued();\n"
"      }\n"
"    }\n"
"  }\n"
"\n"
"  function current() {\n"
"    return entities.find(item => item.entity_id === selectedId) || null;\n"
"  }\n"
"\n"
"  function available(item) {\n"
"    return item && !item.stale && item.state !== 'unavailable' &&\n"
"      item.state !== 'unknown';\n"
"  }\n"
"\n"
"  function supports(item, service) {\n"
"    if (sharedReady) {\n"
"      try { if (!nativeService.status().canControl) return false; }\n"
"      catch (_) { return false; }\n"
"    }\n"
"    return item && ['light', 'switch', 'input_boolean', 'fan'].includes(item.domain) &&\n"
"      !!services[item.domain + '.' + service];\n"
"  }\n"
"\n"
"  function control(service, brightness) {\n"
"    const item = current();\n"
"    if (!connected || !available(item) || pending || queued || nativeBusy ||\n"
"        !supports(item, service)) return;\n"
"    const body = { entity_id: item.entity_id };\n"
"    if (brightness !== undefined) {\n"
"      if (!item.dimmable || !Number.isFinite(brightness)) return;\n"
"      body.brightness_pct = Math.max(1, Math.min(100, Math.round(brightness)));\n"
"    }\n"
"    message = '正在发送控制请求';\n"
"    schedule('service', item.entity_id, { domain: item.domain, service, body });\n"
"    startQueued();\n"
"  }\n"
"\n"
"  function changeBrightness(delta) {\n"
"    const item = current();\n"
"    if (!item || item.brightness === null) return;\n"
"    control('turn_on', item.brightness + delta);\n"
"  }\n"
"\n"
"  function toggleFavorite() {\n"
"    const item = current();\n"
"    if (!item) return;\n"
"    const index = favorites.indexOf(item.entity_id);\n"
"    if (index >= 0) favorites.splice(index, 1);\n"
"    else if (favorites.length < MAX_FAVORITES) favorites.push(item.entity_id);\n"
"    else { message = '关注列表已达 16 个实体'; render(); return; }\n"
"    save('eh_favs', JSON.stringify(favorites));\n"
"    render();\n"
"  }\n"
"\n"
"  function promptUrl() {\n"
"    const openedGeneration = generation;\n"
"    prompt.input({ title: 'Home Assistant 地址', value: url, maxLength: 120 }, value => {\n"
"      if (disposed || openedGeneration !== generation ||\n"
"          value === null || value === undefined || value === '') return;\n"
"      const next = parseUrl(value);\n"
"      if (!next) {\n"
"        message = /^https:/i.test(String(value)) ?\n"
"          '当前 HA 接口不支持 HTTPS，不会降级连接' : '仅支持局域网 HTTP 地址，不允许路径或账号';\n"
"      } else if (next !== url) {\n"
"        invalidate();\n"
"        token = '';\n"
"        httpAllowed = false;\n"
"        url = next;\n"
"        favorites = [];\n"
"        entities = [];\n"
"        selectedId = '';\n"
"        message = '服务端已变更，请重新输入令牌';\n"
"        save('eh_url', url);\n"
"        save('eh_favs', '[]');\n"
"      }\n"
"      render();\n"
"    });\n"
"  }\n"
"\n"
"  function promptToken() {\n"
"    const openedGeneration = generation;\n"
"    prompt.input({ title: '访问令牌（仅本次会话）', value: '',\n"
"      password: true, maxLength: 511 }, value => {\n"
"      if (disposed || openedGeneration !== generation ||\n"
"          value === null || value === undefined || value === '') return;\n"
"      if (typeof value !== 'string' || value.length > 511 || !/^[\\x21-\\x7e]+$/.test(value)) {\n"
"        message = '令牌含空白、控制字符或超过长度限制';\n"
"      } else {\n"
"        invalidate();\n"
"        token = value;\n"
"        message = '令牌已输入，仅保留在本次会话';\n"
"      }\n"
"      render();\n"
"    });\n"
"  }\n"
"\n"
"  function addFavorite() {\n"
"    const openedGeneration = generation;\n"
"    prompt.input({ title: '关注实体 ID', value: '', maxLength: 95 }, value => {\n"
"      if (disposed || openedGeneration !== generation ||\n"
"          value === null || value === undefined || value === '') return;\n"
"      if (!validEntity(value)) message = '实体 ID 格式无效';\n"
"      else if (favorites.includes(value)) message = '该实体已在关注列表';\n"
"      else if (favorites.length >= MAX_FAVORITES) message = '关注列表已达 16 个实体';\n"
"      else {\n"
"        favorites.push(value);\n"
"        message = '已关注 ' + value;\n"
"        save('eh_favs', JSON.stringify(favorites));\n"
"      }\n"
"      render();\n"
"    });\n"
"  }\n"
"\n"
"  function promptSearch() {\n"
"    prompt.input({ title: '搜索名称或实体 ID', value: search, maxLength: 64 }, value => {\n"
"      if (disposed || value === null || value === undefined) return;\n"
"      search = clean(value, 64).trim().toLowerCase();\n"
"      selectedId = '';\n"
"      page = 0;\n"
"      settingsOpen = false;\n"
"      detailOpen = false;\n"
"      render();\n"
"    });\n"
"  }\n"
"\n"
"  function visibleEntities() {\n"
"    return entities.filter(item => {\n"
"      if (filter === 'favorites' && !favorites.includes(item.entity_id)) return false;\n"
"      if (filter === 'controls' &&\n"
"          !['light', 'switch', 'input_boolean', 'fan'].includes(item.domain)) return false;\n"
"      if (filter === 'sensors' && !['sensor', 'binary_sensor'].includes(item.domain)) return false;\n"
"      return !search || (item.name + ' ' + item.entity_id).toLowerCase().includes(search);\n"
"    });\n"
"  }\n"
"\n"
"  function stateText(item) {\n"
"    const translated = { on: '开启', off: '关闭', unavailable: '离线', unknown: '未知' };\n"
"    return (item.stale ? '上次：' : '') +\n"
"      (translated[item.state] || item.state) + (item.unit ? ' ' + item.unit : '');\n"
"  }\n"
"\n"
"  function activeDevices() {\n"
"    return entities.filter(item => available(item) && item.state === 'on' &&\n"
"      ['light', 'switch', 'input_boolean', 'fan'].includes(item.domain)).length;\n"
"  }\n"
"\n"
"  function controlDevices() {\n"
"    return entities.filter(item => ['light', 'switch', 'input_boolean', 'fan']\n"
"      .includes(item.domain)).length;\n"
"  }\n"
"\n"
"  function cardStatus(item) {\n"
"    if (!available(item)) return item.state === 'unavailable' ? '离线' : '未知';\n"
"    if (item.state === 'on') return item.brightness === null ? '开启' : item.brightness + '%';\n"
"    if (item.state === 'off') return '关闭';\n"
"    return fit(stateText(item), 80, 14);\n"
"  }\n"
"\n"
"  function fit(value, width, font) {\n"
"    const text = clean(value, 160);\n"
"    let used = 0, output = '';\n"
"    for (const char of Array.from(text)) {\n"
"      const step = char.charCodeAt(0) > 127 ? font : font * 0.66;\n"
"      if (used + step > width - font) return output + '…';\n"
"      used += step;\n"
"      output += char;\n"
"    }\n"
"    return output;\n"
"  }\n"
"\n"
"  function hide(id, hidden) {\n"
"    if (typeof id === 'object') id.hidden = hidden;\n"
"    else ui.setHidden(id, hidden);\n"
"  }\n"
"\n"
"  function buttonColor(button, color) { button.color = color; }\n"
"  function buttonText(button, text) { button.text = text; }\n"
"\n"
"  function createButton(text, x, y, w, h, action, color, style) {\n"
"    const button = { text, x, y, w, h, action, color, style: style || styles.control,\n"
"      hidden: false, section: 'common' };\n"
"    buttons.push(button);\n"
"    return button;\n"
"  }\n"
"\n"
"  function initializeButtonPool() {\n"
"    for (let i = 0; i < BUTTON_SLOTS; i++) {\n"
"      const slot = { id: 0, target: null };\n"
"      slot.id = ui.button('', 0, 0, 1, 1, () => {\n"
"        const target = slot.target;\n"
"        if (!disposed && target && !target.hidden) target.action();\n"
"      }, colors.surface);\n"
"      ui.setHidden(slot.id, true);\n"
"      buttonPool.push(slot);\n"
"    }\n"
"  }\n"
"\n"
"  function renderButtons() {\n"
"    const view = settingsOpen ? 'settings' : detailOpen ? 'detail' : 'list';\n"
"    const active = buttons.filter(button => button.section === 'common' ||\n"
"      button.section === view || (button.section === 'main' && view === 'list') ||\n"
"      (button.section === 'navigation' && view !== 'settings'));\n"
"    if (active.length > BUTTON_SLOTS) throw new Error('Button pool capacity exceeded');\n"
"    // Hidden controls retain their slots until an explicit page navigation.\n"
"    buttonPool.forEach(slot => {\n"
"      if (slot.target && !active.includes(slot.target)) {\n"
"        slot.target = null;\n"
"        ui.setHidden(slot.id, true);\n"
"      }\n"
"    });\n"
"    active.forEach(button => {\n"
"      let slot = buttonPool.find(entry => entry.target === button);\n"
"      if (!slot) {\n"
"        slot = buttonPool.find(entry => !entry.target);\n"
"        slot.target = button;\n"
"      }\n"
"      ui.setPos(slot.id, button.x, button.y);\n"
"      ui.setSize(slot.id, button.w, button.h);\n"
"      ui.setText(slot.id, button.text);\n"
"      ui.setColor(slot.id, button.color);\n"
"      ui.setStyle(slot.id, button.style);\n"
"      ui.setHidden(slot.id, button.hidden);\n"
"    });\n"
"  }\n"
"  function label(text, x, y, w, h, font, color, icon) {\n"
"    const id = ui.text(text, x, y, font, color, icon ? 1 : 0);\n"
"    ui.setSize(id, w, h);\n"
"    return id;\n"
"  }\n"
"\n"
"  function panel(x, y, w, h, color, radius) {\n"
"    const id = ui.panel(x, y, w, h, color);\n"
"    ui.setStyle(id, { radius: radius || 18, borderWidth: 0 });\n"
"    return id;\n"
"  }\n"
"\n"
"  function iconButton(symbol, x, y, action) {\n"
"    const button = createButton('', x, y, 40, 36, action, colors.surface, styles.icon);\n"
"    const icon = label(symbol, x + 8, y + 5, 26, 26, 24, colors.accent, true);\n"
"    return { button, icon };\n"
"  }\n"
"\n"
"  function placeIconButton(pair, x, y) {\n"
"    pair.button.x = x;\n"
"    pair.button.y = y;\n"
"    ui.setPos(pair.icon, x + 8, y + 5);\n"
"  }\n"
"\n"
"  function pairHidden(pair, value) {\n"
"    hide(pair.button, value);\n"
"    hide(pair.icon, value);\n"
"  }\n"
"\n"
"  function buildUi() {\n"
"    ui.background(colors.background);\n"
"    const pad = 12;\n"
"    const compact = W < 480;\n"
"    const tabColumns = compact ? 2 : 4;\n"
"    const tabWidth = Math.floor((W - pad * 2 - 6 * (tabColumns - 1)) / tabColumns);\n"
"    const tabY = compact ? 88 : 102;\n"
"    const gridY = compact ? 168 : 150;\n"
"    const columns = W >= 800 ? 3 : W >= 560 ? 2 : 1;\n"
"    const footerY = H - 54;\n"
"    const rowCount = Math.max(1, Math.min(2,\n"
"      Math.floor((footerY - gridY + 10) / 88)));\n"
"    const cardWidth = Math.floor((W - pad * 2 - (columns - 1) * 10) / columns);\n"
"    const cardHeight = Math.max(72, Math.floor((footerY - gridY -\n"
"      (rowCount - 1) * 10) / rowCount));\n"
"    const settingsY = compact ? 92 : 96;\n"
"    const settingsStep = compact ? 40 : 44;\n"
"    const out = { cards: [], tabs: [], settings: [], pageSize: columns * rowCount,\n"
"      compact, footerY, gridY };\n"
"    // Panels are allocated before interactive controls so the controls remain\n"
"    // above them in the LVGL draw order.\n"
"    out.heroPanel = panel(pad, 8, W - pad * 2, 72, colors.hero, 20);\n"
"    out.summaryPanel = panel(pad, compact ? 140 : 112, W - pad * 2, 24,\n"
"      colors.surface, 12);\n"
"    out.detailPanel = panel(pad, gridY - 6, W - pad * 2, H - gridY - 64,\n"
"      colors.detail, 18);\n"
"    out.setupPanel = panel(pad, settingsY - 8, W - pad * 2,\n"
"      130 + settingsStep * 3, colors.detail, 18);\n"
"    initializeButtonPool();\n"
"    out.kicker = label('MIJIA HOME', pad + 16, 16, W - 172, 18, 13, colors.heroMuted);\n"
"    out.title = label('我的家', pad + 16, 34, W - 172, 30, 24, colors.text);\n"
"    out.status = label('', pad + 16, 60, W - 178, 18, 14, colors.heroMuted);\n"
"    out.summary = label('', pad, compact ? 144 : 120, W - pad * 2, 22, 15, colors.muted);\n"
"    out.search = iconButton(glyph.search, W - 142, 16, promptSearch);\n"
"    out.refresh = iconButton(glyph.refresh, W - 96, 16, refresh);\n"
"    out.settingsButton = iconButton(glyph.settings, W - 50, 16, () => {\n"
"      settingsOpen = !settingsOpen;\n"
"      render();\n"
"    });\n"
"    [['all', '全屋'], ['favorites', '常用'], ['controls', '设备'], ['sensors', '环境']]\n"
"      .forEach((tab, index) => {\n"
"        const button = createButton(tab[1], pad + index % tabColumns * (tabWidth + 6),\n"
"          tabY + Math.floor(index / tabColumns) * 38, tabWidth, 32, () => {\n"
"            filter = tab[0]; page = 0; selectedId = ''; detailOpen = false; settingsOpen = false; render();\n"
"          }, colors.surface, styles.tab);\n"
"        button.section = 'main';\n"
"        out.tabs.push({ button, key: tab[0] });\n"
"      });\n"
"    for (let i = 0; i < out.pageSize; i++) {\n"
"      const x = pad + i % columns * (cardWidth + 10);\n"
"      const y = gridY + Math.floor(i / columns) * (cardHeight + 10);\n"
"      const button = createButton('', x, y, cardWidth, cardHeight, () => {\n"
"        const item = visibleEntities()[page * out.pageSize + i];\n"
"        if (!item) return;\n"
"        selectedId = item.entity_id;\n"
"        detailOpen = true;\n"
"        render();\n"
"      }, colors.surface, styles.card);\n"
"      button.section = 'list';\n"
"      out.cards.push({\n"
"        button,\n"
"        icon: label('', x + 16, y + 15, 30, 30, 25, colors.accent, true),\n"
"        name: label('', x + 56, y + 12, cardWidth - 132, 24, 18, colors.text),\n"
"        state: label('', x + 56, y + 40, cardWidth - 132, 22, 15, colors.muted),\n"
"        badge: label('', x + cardWidth - 74, y + 18, 62, 24, 14, colors.muted),\n"
"        textWidth: cardWidth - 132\n"
"      });\n"
"    }\n"
"    out.empty = label('', pad, gridY + 28, W - pad * 2, 54, 18, colors.muted);\n"
"    out.entityIcon = label('', pad + 8, gridY + 10, 34, 34, 28, colors.accent, true);\n"
"    out.entityName = label('', pad + 56, gridY + 4, W - 92, 28, 22, colors.text);\n"
"    out.entityId = label('', pad + 56, gridY + 36, W - 92, 24, 15, colors.muted);\n"
"    out.detail = label('', pad + 56, gridY + 72, W - 80, 28, 18, colors.text);\n"
"    out.previous = iconButton(glyph.previous, pad, footerY, () => {\n"
"      if (detailOpen) { selectedId = ''; detailOpen = false; }\n"
"      else if (page > 0) page--;\n"
"      render();\n"
"    });\n"
"    out.next = iconButton(glyph.next, W - 52, footerY, () => {\n"
"      if ((page + 1) * out.pageSize < visibleEntities().length) page++;\n"
"      render();\n"
"    });\n"
"    out.pages = label('', 62, footerY + 7, W - 124, 24, 15, colors.muted);\n"
"    out.previous.button.section = 'navigation';\n"
"    out.next.button.section = 'list';\n"
"    out.favorite = iconButton(glyph.favorite, W - 52, gridY + 4, toggleFavorite);\n"
"    out.on = createButton('开启', pad, H - 46, 76, 36, () => control('turn_on'), colors.selected, styles.control);\n"
"    out.off = createButton('关闭', pad + 84, H - 46, 76, 36, () => control('turn_off'), colors.surface, styles.control);\n"
"    out.minus = createButton('-', W - 144, H - 46, 36, 36, () => changeBrightness(-10), colors.surface, styles.icon);\n"
"    out.level = label('', W - 103, H - 40, 54, 24, 16, colors.text);\n"
"    out.plus = createButton('+', W - 48, H - 46, 36, 36, () => changeBrightness(10), colors.surface, styles.icon);\n"
"    [out.favorite.button, out.on, out.off, out.minus, out.plus].forEach(button => {\n"
"      button.section = 'detail';\n"
"    });\n"
"    const settingsWidth = Math.floor((W - 34) / 2);\n"
"    out.url = label('', pad, settingsY, W - 24, 24, 16, colors.text);\n"
"    out.secret = label('', pad, settingsY + 28, W - 24, 24, 16, colors.muted);\n"
"    out.transport = label('HTTP · 未加密', pad, settingsY + 56, W - 24, 24, 16, colors.warning);\n"
"    const definitions = [\n"
"      ['服务端', promptUrl], ['访问令牌', promptToken],\n"
"      ['允许 HTTP', () => {\n"
"        if (httpAllowed) {\n"
"          invalidate();\n"
"          httpAllowed = false;\n"
"        } else httpAllowed = true;\n"
"        message = httpAllowed ? '已允许本次局域网明文连接' : '已撤销 HTTP 授权';\n"
"        render();\n"
"      }],\n"
"      ['全部实体', () => {\n"
"        if (pending || nativeBusy || queued) { message = '请求结束后才能切换范围'; render(); return; }\n"
"        scope = scope === 'all' ? 'favorites' : 'all';\n"
"        save('eh_scope', scope);\n"
"        selectedId = '';\n"
"        if (connected) { beginStates(); startQueued(); }\n"
"        render();\n"
"      }],\n"
"      ['添加关注', addFavorite], ['连接', connect], ['断开', disconnect]\n"
"    ];\n"
"    definitions.forEach((entry, index) => {\n"
"      out.settings.push(createButton(entry[0], pad + index % 2 * (settingsWidth + 10),\n"
"        settingsY + 88 + Math.floor(index / 2) * settingsStep,\n"
"        settingsWidth, 34, entry[1], index === 5 ? colors.selected : colors.surface, styles.setting));\n"
"    });\n"
"    out.settings.forEach(button => { button.section = 'settings'; });\n"
"    return out;\n"
"  }\n"
"\n"
"  function render() {\n"
"    if (!widgets || disposed) return;\n"
"    const item = current();\n"
"    ui.setText(widgets.kicker, settingsOpen ? 'HOME ASSISTANT' :\n"
"      detailOpen ? 'DEVICE CONTROL' : 'MIJIA HOME');\n"
"    ui.setText(widgets.title, settingsOpen ?\n"
"      (nativeManaged ? '家庭设置' : '连接我的家') : '我的家');\n"
"    ui.setText(widgets.status, fit(message, W - 178, 14));\n"
"    ui.setColor(widgets.status, phase === 'error' ? colors.warning : colors.heroMuted);\n"
"    const filtered = visibleEntities();\n"
"    page = Math.max(0, Math.min(page, Math.max(0, Math.ceil(filtered.length / widgets.pageSize) - 1)));\n"
"    if (!settingsOpen && !filtered.slice(page * widgets.pageSize,\n"
"        (page + 1) * widgets.pageSize).some(item => item.entity_id === selectedId)) {\n"
"      selectedId = '';\n"
"    }\n"
"    widgets.tabs.forEach(tab => {\n"
"      hide(tab.button, settingsOpen || detailOpen);\n"
"      buttonColor(tab.button, tab.key === filter ? colors.selected : colors.surface);\n"
"    });\n"
"    pairHidden(widgets.search, settingsOpen || detailOpen);\n"
"    pairHidden(widgets.refresh, settingsOpen || detailOpen);\n"
"    pairHidden(widgets.settingsButton, settingsOpen);\n"
"    hide(widgets.summaryPanel, settingsOpen || detailOpen);\n"
"    hide(widgets.detailPanel, settingsOpen || !detailOpen || !item);\n"
"    hide(widgets.setupPanel, !settingsOpen);\n"
"    hide(widgets.summary, settingsOpen || detailOpen);\n"
"    ui.setText(widgets.summary, connected ?\n"
"      controlDevices() + ' 个设备 · ' + activeDevices() + ' 个运行中 · ' +\n"
"        (lastCached ? '本地缓存' : '实时状态') :\n"
"      nativeManaged ? '正在读取家庭设备' : '连接后集中查看和控制家庭设备');\n"
"    widgets.cards.forEach((card, index) => {\n"
"      const item = filtered[page * widgets.pageSize + index];\n"
"      [card.button, card.icon, card.name, card.state, card.badge].forEach(id =>\n"
"        hide(id, settingsOpen || detailOpen || !item));\n"
"      if (!item) return;\n"
"      buttonColor(card.button, available(item) && item.state === 'on' ? colors.active :\n"
"        ['sensor', 'binary_sensor'].includes(item.domain) ? colors.sensor : colors.surface);\n"
"      ui.setText(card.icon, glyph[item.domain] || glyph.home);\n"
"      ui.setText(card.name, fit(item.name, card.textWidth, 18));\n"
"      ui.setText(card.state, fit(stateText(item), card.textWidth, 16));\n"
"      ui.setText(card.badge, cardStatus(item));\n"
"      ui.setColor(card.icon, !available(item) ? colors.muted :\n"
"        item.state === 'on' ? colors.accent : colors.muted);\n"
"      ui.setColor(card.state, !available(item) ? colors.muted :\n"
"        item.state === 'on' ? colors.accent : colors.muted);\n"
"      ui.setColor(card.badge, !available(item) ? colors.muted :\n"
"        item.state === 'on' ? colors.accent : colors.muted);\n"
"    });\n"
"    hide(widgets.empty, settingsOpen || (detailOpen ? !!current() : filtered.length > 0));\n"
"    ui.setText(widgets.empty, detailOpen ? '实体已不在当前列表' : search ? '没有匹配的实体' :\n"
"      filter === 'favorites' ? '没有关注实体' :\n"
"      connected ? '没有实体' : '尚未同步实体');\n"
"    pairHidden(widgets.previous, settingsOpen || (!detailOpen && page === 0));\n"
"    pairHidden(widgets.next, settingsOpen || detailOpen ||\n"
"      (page + 1) * widgets.pageSize >= filtered.length);\n"
"    hide(widgets.pages, settingsOpen || detailOpen);\n"
"    ui.setText(widgets.pages, detailOpen ? '设备详情' : fit((page + 1) + ' / ' +\n"
"      Math.max(1, Math.ceil(filtered.length / widgets.pageSize)) + '  ·  ' +\n"
"      filtered.length + ' 个实体' + (search ? '  ·  搜索中' : ''), W - 124, 16));\n"
"    placeIconButton(widgets.previous, 12, detailOpen ? H - 96 : widgets.footerY);\n"
"    [widgets.entityIcon, widgets.entityName, widgets.entityId]\n"
"      .forEach(id => hide(id, settingsOpen || !item));\n"
"    hide(widgets.detail, settingsOpen || !item);\n"
"    pairHidden(widgets.favorite, settingsOpen || !item);\n"
"    if (item) {\n"
"      ui.setText(widgets.entityIcon, glyph[item.domain] || glyph.home);\n"
"      ui.setColor(widgets.entityIcon, available(item) && item.state === 'on' ?\n"
"        colors.accent : colors.muted);\n"
"      ui.setText(widgets.entityName, fit(item.name, W - 92, 22));\n"
"      ui.setText(widgets.entityId, fit(item.entity_id, W - 92, 15));\n"
"      ui.setText(widgets.detail, fit('当前状态 · ' + stateText(item), W - 80, 18));\n"
"      ui.setText(widgets.favorite.icon, favorites.includes(item.entity_id) ? glyph.followed : glyph.favorite);\n"
"      ui.setColor(widgets.favorite.icon, favorites.includes(item.entity_id) ? colors.warning : colors.muted);\n"
"    }\n"
"    const usable = !settingsOpen && connected && available(item) &&\n"
"      !pending && !queued && !nativeBusy;\n"
"    hide(widgets.on, !usable || !supports(item, 'turn_on'));\n"
"    hide(widgets.off, !usable || !supports(item, 'turn_off'));\n"
"    const dimmer = usable && item.dimmable &&\n"
"      item.brightness !== null && supports(item, 'turn_on');\n"
"    [widgets.minus, widgets.level, widgets.plus].forEach(id => hide(id, !dimmer));\n"
"    if (dimmer) ui.setText(widgets.level, item.brightness + '%');\n"
"    [widgets.url, widgets.secret, widgets.transport].forEach(id => hide(id, !settingsOpen));\n"
"    widgets.settings.forEach(id => hide(id, !settingsOpen));\n"
"    ui.setText(widgets.url, fit('家庭中枢 · ' + url, W - 24, 16));\n"
"    ui.setText(widgets.secret, token ? '令牌：已输入（仅本次会话）' :\n"
"      nativeManaged ? '令牌：由本地服务管理' : '令牌：未输入');\n"
"    ui.setText(widgets.transport, httpAllowed || nativeManaged ?\n"
"      '本地网络 · HTTP 明文连接' : '连接前需要确认本地 HTTP 风险');\n"
"    buttonText(widgets.settings[2], httpAllowed ? 'HTTP 已允许' : '允许 HTTP');\n"
"    buttonText(widgets.settings[3], scope === 'favorites' ? '仅关注' : '全部实体');\n"
"    buttonText(widgets.settings[5], connected ? '重新同步' : '连接家庭');\n"
"    buttonColor(widgets.settings[5], colors.selected);\n"
"    renderButtons();\n"
"  }\n"
"\n"
"  function snapshot() {\n"
"    return {\n"
"      phase, message, url, connected, hasToken: !!token, httpAllowed, scope,\n"
"      backend: sharedReady ? 'native-service' : nativeService ? 'unsupported-service' : 'legacy',\n"
"      nativeManaged,\n"
"      favorites: favorites.slice(), filter, search, page, settingsOpen, selectedId,\n"
"      limited, serviceDiscoveryLimited, lastSync, lastCached, nextRefresh,\n"
"      nativeBusy, disposed,\n"
"      view: settingsOpen ? 'settings' : detailOpen ? 'detail' : 'list',\n"
"      pending: pending ? { kind: pending.kind, entityId: pending.entityId,\n"
"        abandoned: !!pending.abandoned } : null,\n"
"      entities: entities.map(item => Object.assign({}, item))\n"
"    };\n"
"  }\n"
"\n"
"  if (W < 320 || H < 360) {\n"
"    ui.background(colors.background);\n"
"    label('米家 HA', 12, 12, Math.max(1, W - 24), 28, 20, colors.text);\n"
"    label('显示区域至少需要 320 × 360', 12, 56, Math.max(1, W - 24), 64, 16, colors.muted);\n"
"    return;\n"
"  }\n"
"  widgets = buildUi();\n"
"  if (!bridgeReady) message = '固件未提供 Home Assistant 接口';\n"
"  render();\n"
"  if (nativeManaged && bridgeReady) connect();\n"
"  ui.onSwipe(direction => {\n"
"    if (disposed || settingsOpen) return;\n"
"    if (detailOpen) {\n"
"      if (direction === 'left' || direction === 'right') {\n"
"        selectedId = '';\n"
"        detailOpen = false;\n"
"        render();\n"
"      }\n"
"      return;\n"
"    }\n"
"    if (direction === 'left' && (page + 1) * widgets.pageSize < visibleEntities().length) page++;\n"
"    else if (direction === 'right' && page > 0) page--;\n"
"    render();\n"
"  });\n"
"  timer = setInterval(tick, 250);\n"
"  globalThis.ESPHomeHA = {\n"
"    refresh, disconnect,\n"
"    settings: () => { settingsOpen = true; render(); },\n"
"    snapshot,\n"
"    dispose: () => {\n"
"      disconnect();\n"
"      disposed = true;\n"
"      buttonPool.forEach(slot => {\n"
"        slot.target = null;\n"
"        ui.setHidden(slot.id, true);\n"
"      });\n"
"      clearInterval(timer);\n"
"      if (bridge && typeof bridge.stop === 'function') bridge.stop();\n"
"    }\n"
"  };\n"
"})();\n";
const char *homeassistant_get_app_js(unsigned int *len) { *len=sizeof(g_homeassistant_app_js)-1; return g_homeassistant_app_js; }
