/* Generated from recorder/app.js. SPDX-License-Identifier: Apache-2.0 */
static const char g_recorder_app_js[] =
"/* SPDX-License-Identifier: Apache-2.0 */\n"
"'use strict';\n"
"\n"
"const size = ui.getSize(), W = size.width, H = size.height;\n"
"const left = 24, top = 24, leftWidth = Math.round((W - 68) * 0.41);\n"
"const right = left + leftWidth + 20, rightWidth = W - right - 24;\n"
"const red = 0xd95068;\n"
"let task = 0, operation = '', stopping = false, pendingClip = '';\n"
"let clips = [], selected = '', page = 0, nextNumber = 1, loaded = false;\n"
"let preferred = '', afterList = '', confirmClip = '', confirmTicks = 0;\n"
"let elapsed = 0, history = Array(28).fill(0);\n"
"\n"
"function text(value, x, y, width, height, font, color) {\n"
"  const id = ui.text(value, x, y, font || 20, color === undefined ? ui.primary : color);\n"
"  ui.setSize(id, width, height); ui.setStyle(id, {ellipsis: 1}); return id;\n"
"}\n"
"function panel(x, y, width, height) {\n"
"  const id = ui.panel(x, y, width, height, ui.card);\n"
"  ui.setStyle(id, {radius: 22, borderWidth: 0}); return id;\n"
"}\n"
"function time(ms) {\n"
"  const seconds = Math.floor(ms / 1000);\n"
"  return String(Math.floor(seconds / 60)).padStart(2, '0') + ':' + String(seconds % 60).padStart(2, '0');\n"
"}\n"
"function title(clip) {\n"
"  const match = /^rec_(\\d+)$/.exec(clip);\n"
"  return match ? '录音 ' + String(Number(match[1])).padStart(3, '0') : clip;\n"
"}\n"
"function errorText(error, kind) {\n"
"  const code = Math.abs(Number(error.error) || 0);\n"
"  if (code === 61 || code === 110) return kind === 'play' ?\n"
"    '播放超时，音频设备未返回数据，请重试' : '麦克风没有返回数据，请重试';\n"
"  return ({16: '音频设备正忙，请稍后重试', 19: '音频设备未就绪',\n"
"    28: '存储空间不足，请删除旧录音', 5: '音频读写失败，请重试',\n"
"    12: '内存不足，请稍后重试'})[code] || '操作失败，请重试';\n"
"}\n"
"\n"
"ui.background(ui.surface);\n"
"panel(left, top, leftWidth, H - 48);\n"
"panel(right, top, rightWidth, H - 48);\n"
"text('新录音', left + 22, 44, leftWidth - 44, 32, 28);\n"
"const status = text('正在读取录音…', left + 22, 88, leftWidth - 44, 48, 20, ui.secondary);\n"
"const clock = ui.number('00:00', left + 22, 142, leftWidth - 44, 64, ui.primary);\n"
"ui.setStyle(clock, {borderWidth: 0});\n"
"text('输入音量', left + 22, 218, leftWidth - 44, 24, 16, ui.secondary);\n"
"const bars = [];\n"
"const step = (leftWidth - 44) / history.length;\n"
"for (let i = 0; i < history.length; i++) {\n"
"  const bar = ui.rect(Math.round(left + 22 + i * step), 277, Math.max(3, Math.floor(step - 4)), 4, ui.surface);\n"
"  ui.setStyle(bar, {radius: 2, borderWidth: 0}); bars.push(bar);\n"
"}\n"
"\n"
"const recordButton = ui.button('开始录音', left + 22, H - 202, leftWidth - 44, 56, record, red);\n"
"const stopButton = ui.button('停止并保存', left + 22, H - 132, leftWidth - 188, 52, stop, ui.accent);\n"
"const cancelButton = ui.button('放弃本次', left + leftWidth - 154, H - 132, 132, 52, cancel, ui.surface);\n"
"text('返回将放弃尚未保存的录音', left + 22, H - 66, leftWidth - 44, 24, 16, ui.secondary);\n"
"\n"
"text('录音列表', right + 22, 44, rightWidth - 150, 32, 28);\n"
"const countLabel = text('0 条', right + rightWidth - 110, 51, 88, 24, 16, ui.secondary);\n"
"ui.setStyle(countLabel, {center: 1});\n"
"const empty = text('还没有录音\\n点击左侧开始录音', right + 38, 206, rightWidth - 76, 100, 20, ui.secondary);\n"
"ui.setStyle(empty, {center: 1, ellipsis: 0});\n"
"const rows = [];\n"
"for (let i = 0; i < 4; i++) {\n"
"  const y = 94 + i * 74;\n"
"  const button = ui.button('', right + 16, y, rightWidth - 32, 66, () => select(page * 4 + i), ui.surface);\n"
"  ui.setStyle(button, {radius: 12, borderWidth: 0});\n"
"  rows.push({button,\n"
"    name: text('', right + 32, y + 8, rightWidth - 64, 27, 20),\n"
"    detail: text('', right + 32, y + 39, rightWidth - 64, 22, 16, ui.secondary)});\n"
"}\n"
"const selectionHint = text('选择录音后可以播放或删除', right + 22, H - 130, rightWidth - 44, 24, 16, ui.secondary);\n"
"const playButton = ui.button('播放', right + 16, H - 80, 154, 44, play, ui.accent);\n"
"const deleteButton = ui.button('删除', right + 182, H - 80, 144, 44, remove, ui.surface);\n"
"const previousButton = ui.button('<', right + rightWidth - 224, H - 80, 64, 44, () => turnPage(-1), ui.surface);\n"
"const pageLabel = text('1 / 1', right + rightWidth - 152, H - 72, 60, 28, 16, ui.secondary);\n"
"ui.setStyle(pageLabel, {center: 1});\n"
"const nextButton = ui.button('>', right + rightWidth - 84, H - 80, 64, 44, () => turnPage(1), ui.surface);\n"
"\n"
"function enable(button, enabled, color, bright) {\n"
"  ui.setStyle(button, {enabled: !!enabled, textColor: enabled && bright ? 0xffffff : ui.secondary});\n"
"  ui.setColor(button, enabled ? color : ui.surface);\n"
"}\n"
"function current() { return clips.find(clip => clip.clip === selected); }\n"
"function controls() {\n"
"  const busy = task !== 0, entry = current();\n"
"  const audio = operation === 'record' || operation === 'play';\n"
"  enable(recordButton, !busy, red, true);\n"
"  enable(stopButton, busy && audio && !stopping, ui.accent, true);\n"
"  enable(cancelButton, busy && operation === 'record' && !stopping, ui.surface, false);\n"
"  enable(playButton, !busy && !!entry && entry.valid !== false, ui.accent, true);\n"
"  enable(deleteButton, !busy && !!entry, confirmClip ? red : ui.surface, !!confirmClip);\n"
"  enable(previousButton, !busy && page > 0, ui.surface, false);\n"
"  enable(nextButton, !busy && (page + 1) * 4 < clips.length, ui.surface, false);\n"
"  ui.setText(recordButton, operation === 'record' ? '录音中' : loaded ? '开始录音' : '重试读取');\n"
"  ui.setText(stopButton, operation === 'play' ? '停止播放' : '停止并保存');\n"
"  ui.setText(deleteButton, confirmClip ? '确认删除' : '删除');\n"
"  for (let i = 0; i < rows.length; i++) ui.setStyle(rows[i].button, {enabled: !busy});\n"
"}\n"
"function drawList() {\n"
"  page = Math.min(page, Math.max(0, Math.ceil(clips.length / 4) - 1));\n"
"  ui.setText(countLabel, clips.length + ' 条');\n"
"  ui.setText(pageLabel, (page + 1) + ' / ' + Math.max(1, Math.ceil(clips.length / 4)));\n"
"  ui.setHidden(empty, clips.length > 0);\n"
"  for (let i = 0; i < rows.length; i++) {\n"
"    const entry = clips[page * 4 + i], row = rows[i];\n"
"    for (const key of ['button', 'name', 'detail']) ui.setHidden(row[key], !entry);\n"
"    if (!entry) continue;\n"
"    ui.setText(row.name, title(entry.clip));\n"
"    ui.setText(row.detail, entry.valid === false ? '文件不完整 · 可删除' :\n"
"      time(entry.durationMs || 0) + '  ·  ' + Math.max(1, Math.round(entry.fileBytes / 1024)) + ' KB');\n"
"    ui.setStyle(row.button, {borderWidth: entry.clip === selected ? 2 : 0, borderColor: ui.accent});\n"
"  }\n"
"  ui.setText(selectionHint, confirmClip ? '再次点击“确认删除”将删除这条录音' :\n"
"    selected ? '已选择：' + title(selected) : '选择录音后可以播放或删除');\n"
"  controls();\n"
"}\n"
"function meter(peak) {\n"
"  history.shift(); history.push(Math.min(1, Math.max(0, Number(peak) / 32768 || 0)));\n"
"  for (let i = 0; i < bars.length; i++) {\n"
"    const height = Math.max(4, Math.round(Math.sqrt(history[i]) * 56));\n"
"    ui.setPos(bars[i], Math.round(left + 22 + i * step), 279 - Math.floor(height / 2));\n"
"    ui.setSize(bars[i], Math.max(3, Math.floor(step - 4)), height);\n"
"    ui.setColor(bars[i], history[i] > 0 ? red : ui.surface);\n"
"  }\n"
"}\n"
"function begin(kind, submit, message) {\n"
"  if (task) return false;\n"
"  try {\n"
"    task = submit(); operation = kind; stopping = false;\n"
"    confirmClip = ''; ui.setText(status, message); controls(); return true;\n"
"  } catch (error) {\n"
"    task = 0; operation = ''; ui.setText(status, '无法开始操作，请稍后重试'); controls(); return false;\n"
"  }\n"
"}\n"
"function refresh(clip, notice) {\n"
"  preferred = clip || ''; afterList = notice || '准备录音';\n"
"  loaded = false;\n"
"  begin('list', () => system.audio.list(), '正在读取录音…');\n"
"}\n"
"function record() {\n"
"  if (task) return;\n"
"  if (!loaded) { refresh('', '准备录音'); return; }\n"
"  pendingClip = 'rec_' + String(nextNumber).padStart(6, '0');\n"
"  if (begin('record', () => system.audio.record({clip: pendingClip, durationMs: 0}), '正在录音')) {\n"
"    elapsed = 0; ui.setText(clock, '00:00'); history.fill(0); meter(0);\n"
"  }\n"
"}\n"
"function stop() {\n"
"  if (!task || stopping || (operation !== 'record' && operation !== 'play')) return;\n"
"  try {\n"
"    system.audio.stop(task); stopping = true;\n"
"    ui.setText(status, operation === 'record' ? '正在保存录音…' : '正在停止播放…'); controls();\n"
"  } catch (error) { ui.setText(status, '停止请求失败，请重试'); }\n"
"}\n"
"function cancel() {\n"
"  if (!task || operation !== 'record' || stopping) return;\n"
"  try { system.hardware.cancel(task); stopping = true; ui.setText(status, '正在放弃录音…'); controls(); }\n"
"  catch (error) { ui.setText(status, '取消请求失败，请重试'); }\n"
"}\n"
"function select(index) {\n"
"  if (task || !clips[index]) return;\n"
"  selected = clips[index].clip; confirmClip = ''; drawList();\n"
"}\n"
"function turnPage(delta) {\n"
"  if (task) return;\n"
"  page = Math.max(0, Math.min(Math.ceil(clips.length / 4) - 1, page + delta));\n"
"  confirmClip = ''; drawList();\n"
"}\n"
"function play() {\n"
"  const entry = current(); if (task || !entry || entry.valid === false) return;\n"
"  if (begin('play', () => system.audio.play({clip: selected, volume: 40}), '正在播放：' + title(selected))) {\n"
"    elapsed = 0; ui.setText(clock, '00:00'); history.fill(0); meter(0);\n"
"  }\n"
"}\n"
"function remove() {\n"
"  if (task || !current()) return;\n"
"  if (confirmClip !== selected) { confirmClip = selected; confirmTicks = 50; drawList(); return; }\n"
"  begin('remove', () => system.audio.remove({clip: selected}), '正在删除录音…');\n"
"}\n"
"function poll() {\n"
"  if (confirmTicks > 0 && --confirmTicks === 0) { confirmClip = ''; drawList(); }\n"
"  if (!task) return;\n"
"  let state;\n"
"  try { state = system.hardware.poll(task); }\n"
"  catch (error) { ui.setText(status, '读取状态失败，正在重试…'); return; }\n"
"  if (!state.done) {\n"
"    if (operation === 'record' || operation === 'play') {\n"
"      elapsed = Number(state.elapsedMs) || 0; ui.setText(clock, time(elapsed));\n"
"      if (operation === 'record') meter(state.peak);\n"
"    }\n"
"    return;\n"
"  }\n"
"  const finished = operation;\n"
"  task = 0; operation = ''; stopping = false;\n"
"  if (finished === 'list' && state.ok) {\n"
"    loaded = true;\n"
"    clips = state.result.clips || [];\n"
"    clips.sort((a, b) => {\n"
"      const an = /^rec_(\\d+)$/.exec(a.clip), bn = /^rec_(\\d+)$/.exec(b.clip);\n"
"      return an && bn ? Number(bn[1]) - Number(an[1]) : b.clip.localeCompare(a.clip);\n"
"    });\n"
"    nextNumber = 1;\n"
"    for (const clip of clips) {\n"
"      const number = /^rec_(\\d+)$/.exec(clip.clip);\n"
"      if (number) nextNumber = Math.max(nextNumber, Number(number[1]) + 1);\n"
"    }\n"
"    if (preferred && clips.some(clip => clip.clip === preferred)) selected = preferred;\n"
"    if (!clips.some(clip => clip.clip === selected)) selected = clips.length ? clips[0].clip : '';\n"
"    if (preferred) page = Math.max(0, Math.floor(clips.findIndex(clip => clip.clip === selected) / 4));\n"
"    ui.setText(status, afterList); drawList(); return;\n"
"  }\n"
"  if (finished === 'record') {\n"
"    elapsed = Number(state.elapsedMs) || elapsed; ui.setText(clock, time(elapsed));\n"
"    history.fill(0); meter(0);\n"
"    refresh(state.ok ? pendingClip : selected, state.ok ? '录音已保存' :\n"
"      Math.abs(state.error) === 125 ? '已放弃本次录音' : errorText(state, 'record')); return;\n"
"  }\n"
"  if (finished === 'remove' && state.ok) { confirmClip = ''; refresh('', '录音已删除'); return; }\n"
"  ui.setText(status, state.ok ? '播放已结束' : errorText(state, finished));\n"
"  drawList();\n"
"}\n"
"\n"
"globalThis.RecorderApp = {record, stop, cancel, play, remove, select, turnPage,\n"
"  state: () => ({task, operation, selected, count: clips.length, elapsed, stopping})};\n"
"drawList(); refresh('', '准备录音'); setInterval(poll, 100);\n";
const char *recorder_get_app_js(unsigned int *len) { *len=sizeof(g_recorder_app_js)-1; return g_recorder_app_js; }
