/* Generated from ouo/app.js. SPDX-License-Identifier: Apache-2.0 */
static const char g_ouo_app_js[] =
"'use strict';\n"
"\n"
"const view = ui.getSize();\n"
"const W = view.width;\n"
"const H = view.height;\n"
"const fallbackId = '02';\n"
"\n"
"const states = {\n"
"  '00': ['离线',       0x29313d, 0x6f7b88, 34, 5,  70, 6, 0, 'offline'],\n"
"  '01': ['启动中',     0x102b36, 0x50d5b7, 40, 10, 68, 8, 1, 'scan'],\n"
"  '02': ['待机',       0x10222c, 0x73dfc0, 42, 12, 58, 8, 1, 'breathe'],\n"
"  '03': ['休眠',       0x171b25, 0x637080, 48, 3,  48, 4, 0, 'sleep'],\n"
"  '04': ['唤醒',       0x16293a, 0x9fd9ff, 46, 16, 72, 7, 1, 'bounce'],\n"
"  '05': ['聆听',       0x112d35, 0x57d7ca, 38, 14, 50, 6, 1, 'listen'],\n"
"  '06': ['表达',       0x2d2239, 0xd6a4ff, 44, 13, 76, 9, 1, 'speak'],\n"
"  '07': ['充电',       0x173026, 0x7ee787, 42, 12, 56, 8, 1, 'charge'],\n"
"  '08': ['低电量',     0x38231f, 0xff9b72, 46, 7,  44, 5, 1, 'slow'],\n"
"  '09': ['更新系统',   0x1b2840, 0x80b6ff, 40, 10, 64, 6, 1, 'scan'],\n"
"  '10': ['开心',       0x143329, 0x70e5a3, 46, 15, 78, 9, 1, 'bounce'],\n"
"  '11': ['兴奋',       0x32272a, 0xffbf69, 52, 18, 82, 10, 1, 'spark'],\n"
"  '12': ['害羞',       0x35252f, 0xf4a6c1, 38, 11, 52, 7, 1, 'shy'],\n"
"  '13': ['平静',       0x192c32, 0x83c5be, 46, 9,  62, 5, 1, 'breathe'],\n"
"  '14': ['难过',       0x20293c, 0x86a9d6, 38, 8,  48, 4, 1, 'sad'],\n"
"  '15': ['生气',       0x3b2223, 0xff716c, 50, 9,  70, 5, 1, 'jitter'],\n"
"  '16': ['惊讶',       0x2b293c, 0xc9a7ff, 30, 22, 32, 18, 1, 'pop'],\n"
"  '17': ['好奇',       0x183239, 0x64d8e6, 40, 13, 56, 7, 1, 'peek'],\n"
"  '18': ['困惑',       0x302a22, 0xe6c36a, 44, 8,  36, 5, 1, 'tilt'],\n"
"  '19': ['自信',       0x222c3b, 0x8db4ff, 50, 11, 72, 7, 1, 'proud'],\n"
"  '30': ['思考中',     0x20233a, 0x9f9cff, 40, 9,  42, 5, 1, 'think'],\n"
"  '31': ['检索资料',   0x122e37, 0x4fd9c8, 36, 10, 50, 6, 1, 'scan'],\n"
"  '32': ['阅读内容',   0x243128, 0x8bd17c, 46, 6,  66, 4, 1, 'read'],\n"
"  '33': ['编写代码',   0x19293a, 0x6eb7ff, 38, 11, 58, 7, 1, 'code'],\n"
"  '34': ['规划步骤',   0x2c2838, 0xc6a3ff, 42, 10, 62, 6, 1, 'plan'],\n"
"  '35': ['等待响应',   0x2d2d31, 0xb4bac3, 44, 8,  46, 5, 1, 'slow'],\n"
"  '36': ['任务成功',   0x153426, 0x69e39b, 50, 15, 82, 9, 1, 'celebrate'],\n"
"  '37': ['需要注意',   0x3b3120, 0xffcc66, 40, 12, 54, 8, 1, 'pulse'],\n"
"  '38': ['发生错误',   0x3b2026, 0xff6f86, 34, 8,  32, 5, 1, 'jitter'],\n"
"  '39': ['正在重试',   0x302a22, 0xf0b768, 40, 10, 56, 6, 1, 'spin'],\n"
"  '40': ['连接服务',   0x192b3a, 0x6bbcff, 38, 12, 60, 7, 1, 'connect'],\n"
"  '41': ['同步数据',   0x162f35, 0x58d4d0, 42, 10, 68, 6, 1, 'scan']\n"
"};\n"
"\n"
"const ids = Object.keys(states);\n"
"let currentId = system.storage.get('emotion') || fallbackId;\n"
"if (!states[currentId]) currentId = fallbackId;\n"
"let active = true;\n"
"let tourTimer = 0;\n"
"let tourIndex = ids.indexOf(currentId);\n"
"let phase = 0;\n"
"let blinkUntil = 0, nextBlink = 35;\n"
"let popPhase = -99, pokePhase = -99, eyeRadius = -1;\n"
"/* The gaze springs towards its target, so a drag feels alive instead of\n"
" * snapping between positions. */\n"
"let gazeX = 0, gazeY = 0, gazeTargetX = 0, gazeTargetY = 0;\n"
"let touching = false;\n"
"let nextGlance = 70, glanceUntil = 0;\n"
"\n"
"ui.background(ui.card);\n"
"/* A rounded backdrop keeps the desktop card shape instead of painting a\n"
" * square colour over its corners. */\n"
"const backdrop = ui.panel(0, 0, W, H, states[currentId][1]);\n"
"ui.setStyle(backdrop, {radius: 24, borderWidth: 0});\n"
"const anchorL = 349, anchorR = 675, eyeCenterY = 262;\n"
"const eyeL = ui.panel(anchorL - 27, eyeCenterY - 64, 54, 128, states[currentId][2]);\n"
"const eyeR = ui.panel(anchorR - 27, eyeCenterY - 64, 54, 128, states[currentId][2]);\n"
"\n"
"function clamp(value, limit) {\n"
"  return value > limit ? limit : value < -limit ? -limit : value;\n"
"}\n"
"\n"
"function setEmotion(id, automatic) {\n"
"  if (!states[id]) id = fallbackId;\n"
"  currentId = id;\n"
"  const s = states[id];\n"
"  tourIndex = ids.indexOf(id);\n"
"  ui.setColor(backdrop, s[1]);\n"
"  ui.setColor(eyeL, s[2]); ui.setColor(eyeR, s[2]);\n"
"  ui.setSize(eyeL, Math.max(20, s[4] * 3), Math.max(36, s[3] * 2));\n"
"  ui.setSize(eyeR, Math.max(20, s[4] * 3), Math.max(36, s[3] * 2));\n"
"  if (!automatic) system.storage.set('emotion', id);\n"
"  popPhase = phase;          /* one short pop so a change is felt, not read */\n"
"  pokePhase = -99;\n"
"}\n"
"\n"
"function setGaze(nx, ny) {\n"
"  gazeTargetX = clamp(Number(nx) || 0, 1);\n"
"  gazeTargetY = clamp(Number(ny) || 0, 1);\n"
"}\n"
"\n"
"function handleAIMessage(message) {\n"
"  let data = message;\n"
"  try {\n"
"    if (typeof message === 'string') data = JSON.parse(message);\n"
"    if (!data || !states[String(data.emotionId)]) throw new Error('invalid emotionId');\n"
"    setEmotion(String(data.emotionId), false);\n"
"    return true;\n"
"  } catch (error) {\n"
"    setEmotion(fallbackId, false);\n"
"    return false;\n"
"  }\n"
"}\n"
"\n"
"function startTour(period) {\n"
"  stopTour();\n"
"  const delay = Math.max(500, Number(period) || 1800);\n"
"  tourTimer = setInterval(() => {\n"
"    tourIndex = (tourIndex + 1) % ids.length;\n"
"    setEmotion(ids[tourIndex], true);\n"
"  }, delay);\n"
"}\n"
"\n"
"function stopTour() {\n"
"  if (tourTimer) clearInterval(tourTimer);\n"
"  tourTimer = 0;\n"
"}\n"
"\n"
"function setActive(value) {\n"
"  active = !!value;\n"
"}\n"
"\n"
"function renderStatic() {\n"
"  renderFrame();\n"
"}\n"
"\n"
"function glance() {\n"
"  if (touching || glanceUntil > phase) return;\n"
"  if (nextGlance > phase) return;\n"
"  gazeTargetX = (Math.sin(phase * 0.7) + Math.sin(phase * 0.23)) * 0.28;\n"
"  gazeTargetY = Math.sin(phase * 0.41) * 0.18;\n"
"  glanceUntil = phase + 12;\n"
"  nextGlance = phase + 70 + (phase % 60);\n"
"}\n"
"\n"
"function renderFrame() {\n"
"  if (!active) return;\n"
"  const s = states[currentId];\n"
"  phase++;\n"
"  const t = phase / 5;\n"
"  const motion = s[8];\n"
"  glance();\n"
"  gazeX += (gazeTargetX - gazeX) * 0.32;\n"
"  gazeY += (gazeTargetY - gazeY) * 0.32;\n"
"\n"
"  let ox = gazeX * 30;\n"
"  let oy = gazeY * 16;\n"
"  const breath = Math.sin(t * 0.22) * 3;\n"
"  if (motion === 'jitter') ox += ((phase % 3) - 1) * 5;\n"
"  if (motion === 'scan') ox += Math.sin(t * 0.55) * 18;\n"
"  if (motion === 'peek') ox += Math.sin(t * 0.16) * 12;\n"
"  if (motion === 'sad') oy += 8;\n"
"  if (motion === 'proud') oy -= 5;\n"
"  if (motion === 'bounce' || motion === 'celebrate') oy += Math.sin(t * 0.42) * 7;\n"
"\n"
"  if (phase >= nextBlink) {\n"
"    blinkUntil = phase + 2;\n"
"    nextBlink = phase + 30 + (phase % 25);\n"
"  }\n"
"\n"
"  const pop = Math.max(0, 1 - (phase - popPhase) / 3);\n"
"  /* Held down: wide, curious eyes. Released: a quick squint and wobble. */\n"
"  const poke = touching ? 1 : Math.max(0, 1 - (phase - pokePhase) / 5);\n"
"  const grow = 1 + 0.16 * pop + (touching ? 0.10 : 0);\n"
"  let eyeW = Math.max(24, s[4] * 3) * grow;\n"
"  let eyeH = Math.max(36, s[3] * 2) * grow;\n"
"  if (!touching && poke > 0) {\n"
"    eyeH *= 0.45 + 0.55 * (1 - poke);\n"
"    eyeW *= 1.05;\n"
"    ox += Math.sin(phase * 1.7) * 7 * poke;\n"
"  }\n"
"  const blinking = !touching && poke === 0 &&\n"
"                   (phase < blinkUntil || motion === 'sleep');\n"
"  if (blinking) { eyeW = 54; eyeH = 6; }\n"
"  const height = Math.max(6, Math.round(eyeH));\n"
"  const width = Math.max(12, Math.round(eyeW));\n"
"  const y = Math.round(eyeCenterY - height / 2 + breath + oy +\n"
"                       (touching ? -4 : 0));\n"
"  const xl = Math.round(anchorL - width / 2 + ox);\n"
"  const xr = Math.round(anchorR - width / 2 + ox);\n"
"  const radius = blinking ? 4 : Math.round(Math.min(width, height) / 2);\n"
"  ui.setPos(eyeL, xl, y); ui.setPos(eyeR, xr, y);\n"
"  ui.setSize(eyeL, width, height); ui.setSize(eyeR, width, height);\n"
"  if (radius !== eyeRadius) {\n"
"    eyeRadius = radius;\n"
"    ui.setStyle(eyeL, {radius: radius, borderWidth: 0});\n"
"    ui.setStyle(eyeR, {radius: radius, borderWidth: 0});\n"
"  }\n"
"}\n"
"\n"
"/* Touching anywhere makes OuO look at the finger; letting go answers with a\n"
" * squint. Swiping keeps switching emotions, as in the original app. */\n"
"ui.onTouch((state, nx, ny) => {\n"
"  if (state === 'down') {\n"
"    touching = true;\n"
"    pokePhase = -99;\n"
"    nextGlance = phase + 70;\n"
"    setGaze((nx - 0.5) * 2.4, (ny - 0.5) * 1.6);\n"
"  } else if (state === 'move') {\n"
"    setGaze((nx - 0.5) * 2.4, (ny - 0.5) * 1.6);\n"
"  } else {\n"
"    touching = false;\n"
"    pokePhase = phase;\n"
"    blinkUntil = phase + 2;\n"
"    setGaze(0, 0);\n"
"  }\n"
"});\n"
"\n"
"ui.onSwipe(direction => {\n"
"  stopTour();\n"
"  const delta = direction === 'left' || direction === 'down' ? 1 : -1;\n"
"  tourIndex = (tourIndex + delta + ids.length) % ids.length;\n"
"  setEmotion(ids[tourIndex], false);\n"
"});\n"
"\n"
"globalThis.VelaMood = {\n"
"  setEmotion,\n"
"  setGaze,\n"
"  handleAIMessage,\n"
"  startTour,\n"
"  stopTour,\n"
"  setActive,\n"
"  renderStatic,\n"
"  isTourRunning: () => tourTimer !== 0,\n"
"  states: ids.slice()\n"
"};\n"
"\n"
"setEmotion(currentId, true);\n"
"setInterval(renderFrame, 50);\n"
"console.log('Vela Mood Console initialized with ' + ids.length + ' original states');\n";
const char *ouo_get_app_js(unsigned int *len) { *len=sizeof(g_ouo_app_js)-1; return g_ouo_app_js; }
