"""Package pinned model assets outside firmware and the existing /data region."""
from pathlib import Path
import hashlib
import json
import shutil
import struct

ws = Path(__file__).resolve().parent.parent
delivery = ws / '04-v3-20260913/espdl-quickapp'
upstream = ws / 'diagnostics/espdl-reference/esp-dl'
assets = [('imagenet', 'imagenet_cls', 'imagenet_cls_mobilenetv2_s8_v1.espdl'),
          ('face_msr', 'human_face_detect', 'human_face_detect_msr_s8_v1.espdl'),
          ('face_mnp', 'human_face_detect', 'human_face_detect_mnp_s8_v1.espdl')]
records, image = [], bytearray()
conversion = {}
for ident, group, filename in assets:
    target = delivery / 'models' / filename
    if group:
        shutil.copyfile(upstream / 'models' / group / 'models/p4' / filename,target)
    blob = target.read_bytes()
    if group:
        assert blob[:4] == b'EDL2'
        encrypt, size, padding = struct.unpack_from('<III', blob, 4)
        assert encrypt == padding == 0 and 16 <= size <= len(blob)-16
    offset = (len(image)+4095) & ~4095
    image.extend(b'\xff' * (offset-len(image)))
    image.extend(blob)
    records.append({'id':ident,'file':filename,'bytes':len(blob),
                    'offset':offset, 'sha256':hashlib.sha256(blob).hexdigest()})
assert len(image) <= 0x400000
(delivery / 'models.bin').write_bytes(image)
manifest = {'upstream':'espressif/esp-dl',
            'revision':'dc380d450835d42f92777121a0cd4fc67d7c3a8c',
            'flash_base':0x800000,'flash_limit':0xc00000,
            'weight_layout':'esp32p4-simd',
            'sd_directory':'/sdcard/espdl','records':records,
            'bundle_bytes':len(image),'bundle_sha256':hashlib.sha256(image).hexdigest()}
(delivery / 'models/manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
header = ['/* Generated by diagnostics/package_espdl_models.py. */',
          '#pragma once', '#include <stddef.h>', '#include <stdint.h>',
          'struct qpk_dl_model_asset { const char *file; uint32_t bytes, offset; uint8_t sha256[32]; };',
          'static const struct qpk_dl_model_asset g_qpk_dl_assets[] = {']
for record in records:
    digest = ','.join('0x'+record['sha256'][i:i+2] for i in range(0,64,2))
    header.append('  {"%s", %u, %u, {%s}},' % (record['file'],record['bytes'],record['offset'],digest))
header.extend(['};','#define QPK_DL_ASSET_COUNT 3','#define QPK_DL_FLASH_BASE 0x800000U',
               '#define QPK_DL_FLASH_SIZE 0x400000U',''])
(delivery / 'overlay/apps/system/desktop/espdl_assets.h').write_text('\n'.join(header))
for name in ['LICENSE']:
    source = upstream / name
    if source.is_file():
        shutil.copyfile(source,delivery / 'models' / ('ESP-DL-'+name))
print(json.dumps(manifest,indent=2))
(delivery / 'evidence/model-conversion.json').write_text(json.dumps(conversion,indent=2)+'\n')
