"""Package the AI guide and pinned, byte-identical firmware examples.

No source is fetched from the network. Updating a pin requires reviewing and
testing the changed example; a build must not silently call new code verified.
"""
from pathlib import Path
import hashlib
import json
import re

WS = Path(__file__).resolve().parent.parent
SYSTEM = WS / '04-v3-20260913/espdl-quickapp/overlay/apps/system'
PINS = {
    'hello': '5afb533340f6a57f8b27af13177d326f6497e62ab8fbde904793a0b7f87db16b',
    'game2048': 'aef46fb6f70d4160a843a0e2a890c8b40b337dfbf3c3e9061c74e84d5bb8b2f8',
    'ouo': '72ec0ffb36e5fcceb9d482b9c8b8760587e81ebcd31afe32ca54b8ba50aa4b0a',
}


def write_changed(path, text):
    data = text.encode('utf-8')
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_bytes() != data:
        path.write_bytes(data)


def extract_literal(source, symbol):
    match = re.search(r'static const char ' + re.escape(symbol) +
                      r'\[\]\s*=\s*((?:"(?:[^"\\]|\\.)*"\s*)+);', source)
    if not match:
        raise ValueError('Cannot extract embedded example: ' + symbol)
    return ''.join(json.loads(piece) for piece in
                   re.findall(r'"(?:[^"\\]|\\.)*"', match.group(1)))


def prepare_qpk_guide(system=SYSTEM):
    desktop, espclaw = system / 'desktop', system / 'espclaw'
    native = (desktop / 'desktop_main.c').read_text(encoding='utf-8')
    examples = [
        ('hello', '你好快应用', 'com.example.hello', '1.0.2',
         extract_literal(native, 'g_hello_qpk_js'),
         'desktop_main.c: g_hello_qpk_js',
         '启动计数、本包存储、按钮、提示、定时更新标签。',
         'ui-layout-fix/evidence/review-light/light-hello.json 与 review-dark/dark-hello.json；'
         'espdl-quickapp/evidence/ui-before-13/light-hello.json 保留了后续版页面记录。'
         '这些是对应旧固件的界面验证，不能代替新应用验收。'),
        ('game2048', '2048', 'com.example.game2048', '1.0.0',
         extract_literal(native, 'g_2048_qpk_js'),
         'desktop_main.c: g_2048_qpk_js',
         '4×4 网格、控件复用、数字、手势、合并算法、最高分。',
         'ui-layout-fix/evidence/review-light/light-2048.json 和 review-dark/dark-2048.json '
         '是已有页面审计。游戏边界和连续操作由本次宿主测试另行验证，不能将页面截图当作全部玩法通过。'),
        ('ouo', 'OuO', 'ouo', '1.0.0',
         (desktop / 'ouo/app.js').read_text(encoding='utf-8'),
         'desktop/ouo/app.js',
         '表情状态、触摸三参数回调、动画、有限定时器。',
         'espdl-quickapp/tests/test_ouo_app.js 覆盖状态、定时器、触摸和帧工作量；'
         'evidence/ouo-touch-boot.json 等为实板专项记录。聆听、充电等文案只是表情状态。'),
    ]
    guide = (espclaw / 'guide/QUICKAPP_GUIDE.md').read_text(encoding='utf-8')
    guide += '\n\n' + (espclaw / 'guide/HARDWARE_API.md').read_text(encoding='utf-8')
    assets = []
    catalog = []
    for ident, name, package, version, source, origin, purpose, evidence in examples:
        digest = hashlib.sha256(source.encode('utf-8')).hexdigest()
        if digest != PINS[ident]:
            raise ValueError(f'{ident} source changed; review tests and update its verification pin')
        manifest = json.dumps(dict(name=name, package=package, versionName=version,
                                   entry='app.js'), ensure_ascii=False, indent=2) + '\n'
        readme = (f'# {name}：ESPClaw 参考项目\n\n'
                  f'设备路径：`/data/qpk/.examples/{ident}/`。\n\n'
                  f'用途：{purpose}\n\n源码来源：`{origin}`，与当前固件对应源代码逐字节一致（LF、UTF-8）。'
                  f'\n\n源码 SHA-256：`{digest}`。\n\n'
                  f'已有证据与边界：{evidence}\n\n'
                  '本次生成器的固定源码/交互测试报告位于 `espdl-quickapp/evidence/qpk-authoring-validation.json`；'
                  '只有报告实际存在且相应测试通过时才可引用其结论。'
                  '这些文件不包含应用用户数据，也不读取 `.data` 或服务配置。\n\n'
                  '阅读顺序：先理解 `app.js` 的状态和渲染函数，再按新任务借用 API。'
                  '示例 package 只用于说明来源，新应用由生成器分配 `ai.<slug>`，不要复用它。'
                  '存储异常提示、按钮大小、主题和内容区尺寸应针对新应用再次检查。\n')
        for filename, text in [('manifest.json', manifest), ('app.js', source), ('README.md', readme)]:
            write_changed(espclaw / 'qpk' / ident / filename, text)
            assets.append((ident, filename, text))
        catalog.append(dict(id=ident, name=name, purpose=purpose,
                            path=f'/data/qpk/.examples/{ident}',
                            files=['README.md', 'manifest.json', 'app.js'],
                            source_sha256=digest, origin=origin, verification=evidence))
    catalog_json = json.dumps({'examples': catalog}, ensure_ascii=False, indent=2) + '\n'
    write_changed(espclaw / 'qpk/catalog.json', catalog_json)

    def literal(text):
        return '\n'.join(json.dumps(line, ensure_ascii=False) for line in text.splitlines(keepends=True))

    output = '/* Generated by diagnostics/prepare_qpk_guide.py; do not edit. */\n'
    output += 'static const char qpk_authoring_guide[] =\n' + literal(guide) + ';\n'
    tools = json.dumps(json.loads((espclaw / 'guide/tools.json').read_text(encoding='utf-8')),
                       ensure_ascii=False, separators=(',', ':'))
    output += 'static const char qpk_authoring_tools[] =\n' + literal(tools) + ';\n'
    output += 'static const char qpk_example_catalog[] =\n' + literal(catalog_json) + ';\n'
    for index, (_, _, text) in enumerate(assets):
        output += f'static const char qpk_asset_{index}[] =\n' + literal(text) + ';\n'
    output += 'static const struct qpk_example_asset qpk_example_assets[] = {\n'
    for index, (ident, filename, _) in enumerate(assets):
        output += f'  {{"{ident}", "{filename}", qpk_asset_{index}}},\n'
    output += '};\n'
    write_changed(desktop / 'glass_qpk_assets.inc', output)
    return catalog


if __name__ == '__main__':
    for item in prepare_qpk_guide():
        print(item['id'], item['source_sha256'])
