/* SPDX-License-Identifier: Apache-2.0 */
#pragma once
#include <nuttx/config.h>
#include <stdio.h>
#define CONFIG_USB_PRINTF(...) printf(__VA_ARGS__)
#define CONFIG_USB_DBG_LEVEL USB_DBG_INFO
#define CONFIG_USB_ALIGN_SIZE 64
#define CONFIG_USB_DCACHE_ENABLE
#define USB_NOCACHE_RAM_SECTION
#define CONFIG_USB_MEMCPY_DISABLE
#define CONFIG_USB_HS
#define CONFIG_USBHOST_MAX_BUS 1
#define CONFIG_USBHOST_MAX_RHPORTS 1
#define CONFIG_USBHOST_MAX_EXTHUBS 1
#define CONFIG_USBHOST_MAX_EHPORTS 4
#define CONFIG_USBHOST_MAX_INTERFACES 8
#define CONFIG_USBHOST_MAX_INTF_ALTSETTINGS 16
#define CONFIG_USBHOST_MAX_ENDPOINTS 3
#define CONFIG_USBHOST_DEV_NAMELEN 24
#define CONFIG_USBHOST_REQUEST_BUFFER_LEN 8192
#define CONFIG_USBHOST_CONTROL_TRANSFER_TIMEOUT 2000
#define CONFIG_USBHOST_PSC_PRIO 50
#define CONFIG_USBHOST_PSC_STACKSIZE 6144
